import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
export function MusicStatsTab({ pieData, difficultyData, getStats, }) {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs(Card, { children: [_jsx(CardHeader, { className: "pb-2", children: _jsx(CardTitle, { className: "text-base sm:text-lg", children: "Distribuci\u00F3n" }) }), _jsx(CardContent, { children: pieData.length > 0 ? (_jsx(ResponsiveContainer, { width: "100%", height: 180, children: _jsxs(PieChart, { children: [_jsx(Pie, { data: pieData, cx: "50%", cy: "50%", innerRadius: 40, outerRadius: 70, dataKey: "value", label: ({ name, value }) => `${name}: ${value}`, labelLine: false, children: pieData.map((entry, i) => (_jsx(Cell, { fill: entry.color }, i))) }), _jsx(Tooltip, {})] }) })) : (_jsx("p", { className: "text-center text-muted-foreground py-8", children: "Sin datos a\u00FAn" })) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { className: "pb-2", children: _jsx(CardTitle, { className: "text-base sm:text-lg", children: "Por Dificultad" }) }), _jsx(CardContent, { children: _jsx(ResponsiveContainer, { width: "100%", height: 180, children: _jsxs(BarChart, { data: difficultyData, children: [_jsx(XAxis, { dataKey: "name", tick: { fontSize: 10 } }), _jsx(YAxis, { allowDecimals: false, tick: { fontSize: 10 } }), _jsx(Tooltip, {}), _jsx(Bar, { dataKey: "piano", name: "Piano", fill: "hsl(var(--foreground))", radius: [4, 4, 0, 0] }), _jsx(Bar, { dataKey: "guitar", name: "Guitarra", fill: "hsl(var(--warning))", radius: [4, 4, 0, 0] })] }) }) })] })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: ['piano', 'guitar'].map(inst => {
                    const s = getStats(inst);
                    const masteredPct = s.total > 0 ? Math.round((s.mastered / s.total) * 100) : 0;
                    return (_jsx(Card, { children: _jsxs(CardContent, { className: "p-4", children: [_jsx("p", { className: "text-base sm:text-lg font-bold mb-1", children: inst === 'piano' ? '🎹 Piano' : '🎸 Guitarra' }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { children: "Dominio" }), _jsxs("span", { children: [masteredPct, "%"] })] }), _jsx(Progress, { value: masteredPct, className: "h-2" }), _jsxs("div", { className: "grid grid-cols-3 gap-2 text-center text-xs pt-2", children: [_jsxs("div", { children: [_jsx("p", { className: "font-bold text-base sm:text-lg", children: s.total }), "Total"] }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-base sm:text-lg text-success", children: s.mastered }), "Dominadas"] }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-base sm:text-lg text-warning", children: s.learning }), "Aprendiendo"] })] })] })] }) }, inst));
                }) })] }));
}
