import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useGoalHierarchy } from '@/hooks/useGoalHierarchy';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Compass, Target, Calendar, CheckCircle2 } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
export default function GoalAlignment() {
    const { data, loading } = useGoalHierarchy();
    if (loading) {
        return (_jsx("div", { className: "container mx-auto px-4 py-24", children: _jsx("p", { className: "text-muted-foreground", children: "Cargando jerarqu\u00EDa de metas..." }) }));
    }
    return (_jsxs("div", { className: "container mx-auto px-4 py-24 space-y-6", children: [_jsxs("header", { children: [_jsxs("h1", { className: "text-3xl font-bold flex items-center gap-2", children: [_jsx(Compass, { className: "h-8 w-8" }), "Conexi\u00F3n Total"] }), _jsx("p", { className: "text-muted-foreground", children: "Visualiza c\u00F3mo tus objetivos trimestrales se conectan con metas mensuales y semanales" })] }), data.length === 0 ? (_jsx(Card, { children: _jsxs(CardContent, { className: "py-12 text-center", children: [_jsx(Target, { className: "h-12 w-12 mx-auto text-muted-foreground mb-4" }), _jsx("p", { className: "text-muted-foreground", children: "No hay objetivos trimestrales definidos" }), _jsx("p", { className: "text-sm text-muted-foreground mt-1", children: "Ve a \"Plan 3 Meses\" para crear objetivos trimestrales" })] }) })) : (_jsx(Accordion, { type: "multiple", className: "space-y-4", children: data.map((goal) => (_jsxs(AccordionItem, { value: goal.id, className: "border rounded-lg px-4", children: [_jsx(AccordionTrigger, { className: "hover:no-underline", children: _jsxs("div", { className: "flex items-center gap-3 text-left", children: [_jsx(Target, { className: "h-5 w-5 text-primary flex-shrink-0" }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold", children: goal.title }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx(Badge, { variant: "outline", children: goal.area }), _jsxs(Badge, { variant: "secondary", children: [goal.progress, "%"] })] })] })] }) }), _jsxs(AccordionContent, { className: "space-y-4 pt-2", children: [_jsx(Progress, { value: goal.progress, className: "h-2" }), goal.monthlyGoals.length > 0 ? (goal.monthlyGoals.map((monthly) => (_jsxs(Card, { className: "border-l-4 border-l-primary/50", children: [_jsx(CardHeader, { className: "pb-2", children: _jsxs(CardTitle, { className: "text-sm flex items-center gap-2", children: [_jsx(Calendar, { className: "h-4 w-4" }), monthly.title, monthly.completed && _jsx(CheckCircle2, { className: "h-4 w-4 text-green-500" })] }) }), _jsxs(CardContent, { children: [_jsx(Progress, { value: monthly.progress, className: "h-1.5 mb-2" }), monthly.weeklyObjectives.length > 0 && (_jsx("div", { className: "space-y-1", children: monthly.weeklyObjectives.map((week) => (_jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx(CheckCircle2, { className: `h-3 w-3 ${week.completed ? 'text-green-500' : 'text-muted-foreground'}` }), _jsxs("span", { className: week.completed ? 'line-through text-muted-foreground' : '', children: ["Semana ", week.weekNumber, ": ", week.title] })] }, week.id))) }))] })] }, monthly.id)))) : (_jsx("p", { className: "text-sm text-muted-foreground", children: "Sin metas mensuales asociadas" }))] })] }, goal.id))) }))] }));
}
