import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Progress } from '@/components/ui/progress';
import { cn } from '@/lib/utils';
export function AreaResultsCard({ areaId, metrics, getCurrentValue, targetForPeriod, editable, onMetricChange, periodLabel }) {
    return (_jsxs("div", { className: "space-y-2.5", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-muted-foreground/40" }), _jsxs("span", { className: "text-xs font-semibold text-muted-foreground uppercase tracking-wider", children: ["Resultados", periodLabel && _jsxs("span", { className: "font-normal lowercase ml-1", children: ["(", periodLabel, ")"] })] })] }), _jsx("div", { className: "space-y-2", children: metrics.map(m => {
                    const current = getCurrentValue(m.id);
                    const target = targetForPeriod(m);
                    const progress = target > 0 ? Math.min(100, Math.round((current / target) * 100)) : current > 0 ? 100 : 0;
                    const hasTarget = target > 0;
                    return (_jsxs("div", { className: "bg-muted/20 rounded-lg p-2 space-y-1", children: [_jsxs("div", { className: "flex items-center justify-between gap-2", children: [_jsx("span", { className: "text-xs text-muted-foreground truncate", children: m.label }), _jsxs("div", { className: "flex items-center gap-1 shrink-0", children: [editable ? (_jsx("input", { type: "number", step: 0.5, min: 0, className: "w-14 h-6 text-xs text-right rounded-md border bg-transparent focus:outline-none focus:ring-1 focus:ring-primary", value: current, onChange: e => onMetricChange?.(m.id, parseFloat(e.target.value) || 0) })) : (_jsx("span", { className: "text-xs font-semibold tabular-nums", children: current })), _jsxs("span", { className: "text-[10px] text-muted-foreground", children: ["/ ", target] }), _jsx("span", { className: "text-[10px] text-muted-foreground ml-0.5", children: m.unit })] })] }), hasTarget && (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Progress, { value: progress, className: "h-1.5 flex-1" }), _jsxs("span", { className: cn("text-[10px] font-mono font-semibold w-8 text-right", progress >= 100 ? "text-green-500" : progress >= 50 ? "text-amber-500" : "text-muted-foreground"), children: [progress, "%"] })] })), !editable && current === 0 && (_jsx("p", { className: "text-[9px] text-muted-foreground/50 italic", children: "Sin datos de semanas anteriores" }))] }, m.id));
                }) })] }));
}
