/* Auto-generated Spanish translations for exercise names */
export const ES_NAMES: Record<string, string> = {
  "1000": "Single pierna reverse elevación de pantorrillas con banda",
  "1001": "Single pierna sentadilla dividida con banda",
  "1002": "Acostado recto elevación de piernas con banda",
  "1003": "Sentadilla remo con banda",
  "1004": "Sentadilla con banda",
  "1005": "De pie abdominales con banda",
  "1007": "De pie twisting abdominales con banda",
  "1008": "Escalón-arriba con banda",
  "1009": "Stiff pierna peso muerto con banda",
  "1010": "Recto pierna peso muerto con banda",
  "1011": "Sentado twist con banda",
  "1012": "Twisting press overhead con banda",
  "1013": "Supino jalón con banda",
  "1014": "V-arriba con banda",
  "1015": "Vertical pallof press con banda",
  "1016": "Curl de muñeca con banda",
  "1017": "Y-raise con banda",
  "1018": "Encogimiento con banda",
  "1022": "De pie deltoides posterior remo con banda",
  "1023": "Recto espalda stiff pierna peso muerto con banda",
  "1160": "Burpee",
  "1167": "Dynamic pecho stretch (hombre)",
  "1201": "Burpee con mancuerna",
  "1253": "Donkey elevación de pantorrillas con máquina",
  "1254": "Press de banca con banda",
  "1255": "Declinado pullover con barra",
  "1256": "Agarre invertido declinado press de banca con barra",
  "1257": "Agarre invertido inclinado press de banca con barra",
  "1258": "Ancho agarre invertido press de banca con barra",
  "1259": "Behind cabeza pecho stretch",
  "1260": "Declinado one brazo press con polea",
  "1261": "Declinado press con polea",
  "1262": "One brazo declinado pecho aperturas con polea",
  "1263": "One brazo aperturas en exercise pelota con polea",
  "1264": "One brazo inclinado aperturas en exercise pelota con polea",
  "1265": "One brazo inclinado press con polea",
  "1266": "One brazo inclinado press en exercise pelota con polea",
  "1267": "One brazo press en exercise pelota con polea",
  "1268": "Press en exercise pelota con polea",
  "1269": "De pie arriba recto crossovers con polea",
  "1270": "Upper pecho crossovers con polea",
  "1271": "Pecho y frontal of hombro stretch",
  "1272": "Pecho stretch con exercise pelota",
  "1273": "Clap flexión de brazos",
  "1274": "Deep flexión de brazos",
  "1275": "Drop flexión de brazos",
  "1276": "Declinado one brazo aperturas con mancuerna",
  "1277": "Aperturas en exercise pelota con mancuerna",
  "1278": "Inclinado aperturas en exercise pelota con mancuerna",
  "1279": "Inclinado one brazo aperturas con mancuerna",
  "1280": "Inclinado one brazo aperturas en exercise pelota con mancuerna",
  "1281": "Inclinado one brazo press con mancuerna",
  "1282": "Inclinado one brazo press en exercise pelota con mancuerna",
  "1283": "Inclinado press en exercise pelota con mancuerna",
  "1284": "Acostado pullover en exercise pelota con mancuerna",
  "1285": "One brazo banca aperturas con mancuerna",
  "1286": "One brazo pecho aperturas en exercise pelota con mancuerna",
  "1287": "One brazo declinado pecho press con mancuerna",
  "1288": "One brazo aperturas en exercise pelota con mancuerna",
  "1289": "One brazo inclinado pecho press con mancuerna",
  "1290": "One brazo press en exercise pelota con mancuerna",
  "1291": "One brazo pullover en exercise pelota con mancuerna",
  "1292": "One pierna aperturas en exercise pelota con mancuerna",
  "1293": "Press en exercise pelota con mancuerna",
  "1294": "Pullover extensión de cadera en exercise pelota con mancuerna",
  "1295": "Pullover en exercise pelota con mancuerna",
  "1296": "Exercise pelota pike flexión de brazos",
  "1297": "Isometric pecho squeeze",
  "1298": "One brazo suelo press con peso ruso",
  "1299": "Inclinado pecho press con máquina",
  "1300": "Declinado pecho press con máquina",
  "1301": "Inner pecho press con máquina",
  "1302": "Pecho pass con balón",
  "1303": "Pecho push from 3 point stance con balón",
  "1304": "Pecho push multiple response con balón",
  "1305": "Pecho push single response con balón",
  "1306": "Plyo flexión de brazos",
  "1307": "Flexión de brazos en bosu pelota",
  "1308": "Smith agarre ancho press de banca",
  "1309": "Smith agarre ancho declinado press de banca",
  "1310": "Drop flexión de brazos con con peso",
  "1311": "Ancho mano flexión de brazos",
  "1312": "Pecho push con run release con balón",
  "1313": "Unilateral remo con máquina",
  "1314": "Extensión de espalda en exercise pelota",
  "1316": "Inclinado brazo pullover con barra",
  "1317": "Agarre invertido inclinado banca remo con barra",
  "1318": "Inclinado banca remo con polea",
  "1319": "Palm rotational remo con polea",
  "1320": "Cuerda crossover remo sentado con polea",
  "1321": "Cuerda elevated remo sentado con polea",
  "1322": "Cuerda extension inclinado banca remo con polea",
  "1323": "Cuerda remo sentado con polea",
  "1324": "Upper remo con polea",
  "1325": "Agarre ancho posterior jalón behind cuello con polea",
  "1326": "Supina",
  "1327": "Agarre estrecho supina",
  "1328": "Acostado deltoides posterior remo con mancuerna",
  "1329": "Palm rotational remo inclinado con mancuerna",
  "1330": "Agarre invertido inclinado banca one brazo remo con mancuerna",
  "1331": "Agarre invertido inclinado banca two brazo remo con mancuerna",
  "1332": "Exercise pelota alterno brazo ups",
  "1333": "Exercise pelota extensión de espalda con brazos extended",
  "1334": "Exercise pelota extensión de espalda con manos behind cabeza",
  "1335": "Exercise pelota extensión de espalda con rodillas off suelo",
  "1336": "Exercise pelota extensión de espalda con rotation",
  "1338": "Exercise pelota hug",
  "1339": "Exercise pelota lat stretch",
  "1341": "Exercise pelota lower espalda stretch (pyramid)",
  "1342": "Exercise pelota acostado side lat stretch",
  "1343": "Exercise pelota boca abajo elevación de piernas",
  "1344": "Ez barra agarre invertido remo inclinado",
  "1345": "Two brazo remo con peso ruso",
  "1346": "Kneeling lat stretch",
  "1347": "One brazo lateral ancho jalón con máquina",
  "1348": "Agarre invertido vertical remo con máquina",
  "1349": "Reverse t-barra remo con máquina",
  "1350": "Remo sentado con máquina",
  "1351": "T-barra agarre invertido remo con máquina",
  "1352": "Lower espalda curl",
  "1353": "Catch y overhead throw con balón",
  "1354": "Overhead slam con balón",
  "1355": "One brazo against pared",
  "1356": "One brazo lateral alto remo con máquina",
  "1358": "Side acostado suelo stretch",
  "1359": "Smith remo inclinado",
  "1360": "Smith one brazo remo",
  "1361": "Smith agarre invertido remo inclinado",
  "1362": "Sphinx",
  "1363": "Columna stretch",
  "1364": "De pie pelvic tilt",
  "1365": "Upper espalda stretch",
  "1366": "Perro boca arriba",
  "1367": "Agarre ancho posterior dominada",
  "1368": "Ankle circles",
  "1369": "Two piernas elevación de pantorrillas -  v. 2 con banda (banda under both legs)",
  "1370": "Suelo elevación de pantorrillas con barra",
  "1371": "Sentado elevación de pantorrillas con barra",
  "1372": "De pie elevación de pantorrillas con barra",
  "1373": "Bodyweight de pie elevación de pantorrillas",
  "1374": "Cajón jump abajo con one pierna stabilization",
  "1375": "De pie elevación de pantorrillas con polea",
  "1376": "De pie one pierna elevación de pantorrillas con polea",
  "1377": "Pantorrilla stretch con manos against pared",
  "1378": "Pantorrilla stretch con cuerda",
  "1379": "Sentado elevación de pantorrillas con mancuerna",
  "1380": "Sentado one pierna elevación de pantorrillas - martillo grip con mancuerna",
  "1381": "Sentado one pierna elevación de pantorrillas - palm arriba con mancuerna",
  "1382": "Exercise pelota en el pared elevación de pantorrillas",
  "1383": "Hack elevación de pantorrillas",
  "1384": "Hack one pierna elevación de pantorrillas",
  "1385": "Sentado sentadilla elevación de pantorrillas en prensa de piernas máquina con máquina",
  "1386": "One pierna donkey elevación de pantorrillas",
  "1387": "One pierna suelo elevación de pantorrillas",
  "1388": "Peroneals stretch",
  "1389": "Posterior tibialis stretch",
  "1390": "Sentado pantorrilla stretch (hombre)",
  "1391": "Trineo pantorrilla press en prensa de piernas",
  "1392": "Trineo one pierna pantorrilla press en prensa de piernas",
  "1393": "Smith one pierna suelo elevación de pantorrillas",
  "1394": "Smith reverse pantorrilla raises",
  "1395": "Smith sentado one pierna elevación de pantorrillas",
  "1396": "Smith dedo del pie raise",
  "1397": "De pie pantorrillas",
  "1398": "De pie pantorrillas pantorrilla stretch",
  "1399": "Banca fondo en suelo",
  "1401": "Muscle-arriba (en vertical barra)",
  "1403": "Cuello side stretch",
  "1405": "Espalda pec stretch",
  "1407": "Pantorrilla push stretch con manos against pared",
  "1408": "Cadera lift con banda",
  "1409": "Puente de glúteos con barra",
  "1410": "Lateral zancada con barra",
  "1411": "Palms abajo curl de muñeca over un banca con barra",
  "1412": "Palms arriba curl de muñeca over un banca con barra",
  "1413": "Reverse one brazo curl con polea",
  "1414": "One brazo curl invertido predicador con mancuerna",
  "1415": "One brazo sentado neutral curl de muñeca con mancuerna",
  "1416": "Exercise pelota one pierna boca abajo lower cuerpo rotation",
  "1417": "Exercise pelota one legged diagonal kick isquiotibial curl",
  "1418": "Hug keens a pecho",
  "1419": "Iron cross stretch",
  "1420": "Kneeling jump sentadilla",
  "1421": "Modified flexión de brazos a antebrazos",
  "1422": "Pelvic tilt into bridge",
  "1423": "Reverse hyper en plano banca",
  "1424": "Sentado glúteo stretch",
  "1425": "Trineo 45 degrees one prensa de piernas",
  "1426": "Smith sentado curl de muñeca",
  "1427": "Recto pierna outer cadera abductor",
  "1428": "Muñeca circles",
  "1429": "Agarre ancho dominada",
  "1430": "Pecho fondo (en dip-pull-up cage)",
  "1431": "De pie supina con asistido",
  "1432": "De pie dominada con asistido",
  "1433": "Smith sentadilla frontal (clean grip)",
  "1434": "Smith bajo barra sentadilla",
  "1435": "Bajo barra sentadilla con barra",
  "1436": "Alto barra sentadilla con barra",
  "1437": "Finger curls con mancuerna",
  "1438": "Sentado two brazo press militar con peso ruso",
  "1439": "Gripless encogimiento v. 2 con máquina",
  "1441": "Over banca one brazo reverse curl de muñeca con mancuerna",
  "1451": "Sentado fondo con máquina",
  "1452": "Sentado abdominales con máquina",
  "1456": "De pie agarre estrecho press militar con barra",
  "1457": "De pie ancho press militar con barra",
  "1458": "Ez barra sentado curls",
  "1459": "Romanian peso muerto con mancuerna",
  "1460": "Walking zancada",
  "1461": "Full sentadilla con barra (back pov)",
  "1462": "Full sentadilla con barra (side pov)",
  "1463": "Trineo 45° prensa de piernas (side pov)",
  "1464": "Trineo 45в° prensa de piernas (back pov)",
  "1466": "Twist cadera lift",
  "1467": "Push-arriba en antebrazos",
  "1468": "Crab twist tocarse los dedos",
  "1471": "Inchworm",
  "1472": "Forward jump",
  "1473": "Backward jump",
  "1476": "One pierna sentadilla",
  "1479": "Inclinado pecho press v. 2 con máquina",
  "1489": "Sissy sentadilla",
  "1490": "De pie elevación de pantorrillas (en a staircase)",
  "1494": "Butterfly yoga pose",
  "1495": "Oblique abdominales v. 2",
  "1496": "Sledge martillo",
  "1511": "Isquiotibial stretch",
  "1512": "Un cuatro patas squad stretch",
  "1545": "Full zercher sentadilla con barra",
  "1548": "Chair pierna extended stretch",
  "1559": "Exercise pelota cadera flexor stretch",
  "1560": "Exercise pelota sentado isquiotibial stretch",
  "1564": "Intermediate cadera flexor y cuádriceps stretch",
  "1576": "Pierna arriba isquiotibial stretch",
  "1582": "Reclining big dedo del pie pose con cuerda",
  "1585": "Runners stretch",
  "1587": "Sentado ancho angle pose sequence",
  "1599": "De pie isquiotibial y pantorrilla stretch con strap",
  "1604": "El mejor estiramiento del mundo",
  "1614": "Curl predicador v. 2 con máquina",
  "1615": "Martillo grip curl predicador con máquina",
  "1616": "Agarre invertido curl predicador con máquina",
  "1617": "Declinado one brazo martillo press con mancuerna",
  "1618": "Inclinado martillo press en exercise pelota con mancuerna",
  "1619": "Inclinado one brazo martillo press con mancuerna",
  "1620": "Inclinado one brazo martillo press en exercise pelota con mancuerna",
  "1621": "One brazo martillo press en exercise pelota con mancuerna",
  "1622": "One brazo agarre invertido press con mancuerna",
  "1623": "Palms in inclinado press de banca con mancuerna",
  "1624": "Reverse press de banca con mancuerna",
  "1625": "Smith máquina declinado agarre estrecho press de banca",
  "1626": "Smith máquina reverse declinado agarre estrecho press de banca",
  "1627": "Ez barra agarre estrecho curl predicador",
  "1628": "Ez barra spider curl",
  "1629": "De pie agarre ancho bíceps curl con barra",
  "1630": "Agarre estrecho curl con polea",
  "1631": "Curl de concentración con polea",
  "1632": "Drag curl con polea",
  "1633": "One brazo curl predicador con polea",
  "1634": "Acostado bíceps curl con polea",
  "1635": "One brazo curl invertido predicador con polea",
  "1636": "Overhead curl con polea",
  "1637": "Overhead curl en exercise pelota con polea",
  "1638": "Jalón bíceps curl con polea",
  "1639": "Cuerda martillo curl predicador con polea",
  "1640": "Cuerda one brazo martillo curl predicador con polea",
  "1641": "Sentado curl con polea",
  "1642": "Sentado one brazo curl de concentración con polea",
  "1643": "Sentado overhead curl con polea",
  "1644": "Squatting curl con polea",
  "1645": "Two brazo curl en inclinado banca con polea",
  "1646": "Alterno martillo curl predicador con mancuerna",
  "1647": "Alterno curl predicador con mancuerna",
  "1648": "Alterno sentado curl martillo con mancuerna",
  "1649": "Alterno bíceps curl con pierna raised en exercise pelota con mancuerna",
  "1650": "Alterno sentado bíceps curl en exercise pelota con mancuerna",
  "1651": "Bíceps curl zancada con bowling motion con mancuerna",
  "1652": "Bíceps curl en exercise pelota con pierna raised con mancuerna",
  "1653": "Bíceps curl con stork stance con mancuerna",
  "1654": "Bíceps curl reverse con mancuerna",
  "1655": "Bíceps curl sentadilla con mancuerna",
  "1656": "Bíceps curl v sit en bosu pelota con mancuerna",
  "1657": "Cross cuerpo curl martillo v. 2 con mancuerna",
  "1658": "Zancada con bíceps curl con mancuerna",
  "1659": "Curl martillo en exercise pelota con mancuerna",
  "1660": "Kneeling bíceps curl exercise pelota con mancuerna",
  "1661": "Acostado boca arriba bíceps curl con mancuerna",
  "1662": "Acostado ancho curl con mancuerna",
  "1663": "One brazo martillo curl predicador con mancuerna",
  "1664": "Alto curl con mancuerna",
  "1665": "One brazo boca abajo curl con mancuerna",
  "1666": "One brazo boca abajo curl martillo con mancuerna",
  "1667": "One brazo reverse spider curl con mancuerna",
  "1668": "One brazo sentado bíceps curl en exercise pelota con mancuerna",
  "1669": "One brazo sentado curl martillo con mancuerna",
  "1670": "One brazo de pie curl con mancuerna",
  "1671": "One brazo de pie curl martillo con mancuerna",
  "1672": "One brazo zottman curl predicador con mancuerna",
  "1673": "Curl predicador over exercise pelota con mancuerna",
  "1674": "Boca abajo curl inclinado martillo con mancuerna",
  "1675": "Reverse spider curl con mancuerna",
  "1676": "Sentado alterno curl martillo en exercise pelota con mancuerna",
  "1677": "Sentado bíceps curl con mancuerna",
  "1678": "Sentado curl martillo con mancuerna",
  "1679": "Sentado one brazo bíceps curl en exercise pelota con pierna raised con mancuerna",
  "1680": "De pie one brazo curl over inclinado banca con mancuerna",
  "1682": "Ez barra sentado agarre estrecho curl de concentración",
  "1683": "Smith máquina bíceps curl",
  "1684": "Subida al cajón single pierna balance con bíceps curl con mancuerna",
  "1685": "Sentadilla a overhead reach",
  "1686": "Sentadilla a overhead reach con twist",
  "1687": "Posterior escalón a overhead reach",
  "1688": "Zancada con twist",
  "1689": "Push y pull bodyweight",
  "1700": "Push press con mancuerna",
  "1701": "Agarre estrecho flexión de brazos con balón",
  "1705": "Sentadilla en bosu pelota",
  "1707": "Boca abajo twist en stability pelota",
  "1708": "Acostado pantorrillas stretch con asistido",
  "1709": "Acostado glúteos stretch con asistido",
  "1710": "Acostado gluteus y piriformis stretch con asistido",
  "1712": "Side acostado adductor stretch con asistido",
  "1713": "Boca abajo acostado cuádriceps stretch con asistido",
  "1714": "Boca abajo rectus femoris stretch con asistido",
  "1716": "Sentado pectoralis major stretch con stability pelota con asistido",
  "1717": "Sentadilla remo con polea (con cuerda attachment)",
  "1718": "Sentado agarre estrecho behind cuello extensión de tríceps con barra",
  "1719": "Inclinado agarre estrecho press de banca con barra",
  "1720": "Acostado espalda of el cabeza tríceps extension con barra",
  "1721": "Agarre invertido francesa con barra",
  "1722": "Alto pulley overhead tríceps extension con polea",
  "1723": "One brazo tríceps pushdown con polea",
  "1724": "Cuerda alto pulley overhead tríceps extension con polea",
  "1725": "Cuerda inclinado tríceps extension con polea",
  "1726": "Cuerda acostado en suelo tríceps extension con polea",
  "1727": "De pie agarre invertido one brazo overhead tríceps extension con polea",
  "1728": "Two brazo tríceps kickback con polea",
  "1729": "Acostado alterno extension con mancuerna",
  "1730": "Sentado inclinado over alterno kickback con mancuerna",
  "1731": "Agarre estrecho press con mancuerna",
  "1732": "Forward zancada extensión de tríceps con mancuerna",
  "1733": "Inclinado two brazo extension con mancuerna",
  "1734": "Kickbacks en exercise pelota con mancuerna",
  "1735": "Acostado single extension con mancuerna",
  "1736": "One brazo french press en exercise pelota con mancuerna",
  "1737": "Sentado inclinado over extensión de tríceps con mancuerna",
  "1738": "Sentado agarre invertido one brazo overhead tríceps extension con mancuerna",
  "1739": "De pie alterno tríceps kickback con mancuerna",
  "1740": "De pie inclinado over one brazo extensión de tríceps con mancuerna",
  "1741": "De pie inclinado over two brazo extensión de tríceps con mancuerna",
  "1742": "Tríceps kickback con stork stance con mancuerna",
  "1743": "Twisting press de banca con mancuerna",
  "1744": "Exercise pelota fondo",
  "1745": "Exercise pelota sentado tríceps stretch",
  "1746": "Exercise pelota boca arriba extensión de tríceps",
  "1747": "Ez barra french press en exercise pelota",
  "1748": "Ez barra acostado agarre estrecho extensión de tríceps behind cabeza",
  "1749": "Ez barra de pie french press",
  "1750": "Boca arriba pecho throw con balón",
  "1751": "Pin presses con barra",
  "1752": "Smith máquina inclinado tríceps extension",
  "1753": "Three banca fondo",
  "1754": "Three banca dips con con peso",
  "1755": "Tríceps dips con con peso",
  "1756": "Single pierna peso muerto con barra",
  "1757": "Single pierna peso muerto con mancuerna",
  "1758": "Abdominales con asistido",
  "1759": "Single pierna sentadilla  hombre (pistol)",
  "1760": "Sentadilla copa con mancuerna",
  "1761": "Colgando oblique elevación de rodillas",
  "1763": "Hombro grip dominada",
  "1764": "Colgando pierna cadera raise",
  "1765": "Remo vertical con mancuerna (back pov)",
  "1766": "Self asistido inverse curl de piernas",
  "1767": "Tríceps fondo en alto paralelas barras con con peso",
  "1769": "Bodyweight side acostado bíceps curl",
  "1770": "Bíceps curl de piernas de concentración",
  "1771": "Bodyweight kneeling extensión de tríceps",
  "1772": "Elbow lift - reverse push-arriba",
  "1773": "One brazo towel remo",
  "1774": "Side bridge abducción de cadera",
  "1775": "Side plancha aducción de cadera",
  "2133": "Paseo del granjero",
  "2135": "Frontal plancha con con peso",
  "2136": "Cuban press v. 2 con mancuerna",
  "2137": "Arnold press con mancuerna",
  "2138": "Stationary bike run v. 3",
  "2139": "Manos bike",
  "2141": "Walk elliptical cross trainer",
  "2142": "Ski ergometer",
  "2143": "De pie around world con mancuerna",
  "2144": "Sentado pecho press con polea",
  "2186": "Ez barra declinado extensión de tríceps",
  "2187": "Reverse agarre estrecho press de banca con barra",
  "2188": "Sentado extensión de tríceps con mancuerna",
  "2189": "Dumbbells sentado extensión de tríceps",
  "2202": "Roller cadera stretch",
  "2203": "Roller sentado hombro flexor depresor retractor",
  "2204": "Roller cuerpo saw",
  "2205": "Roller cadera lat stretch",
  "2206": "Roller reverse abdominales",
  "2207": "Roller side lat stretch",
  "2208": "Roller espalda stretch",
  "2209": "Roller sentado single pierna hombro flexor depresor retractor",
  "2271": "Left hook. boxing",
  "2285": "Pullover con máquina",
  "2286": "Extensión de cadera v. 2 con máquina",
  "2287": "Alterno prensa de piernas con máquina",
  "2288": "Gripper manos con máquina",
  "2289": "Pantorrilla press con máquina",
  "2292": "Deltoides posterior raise con mancuerna",
  "2293": "De pie zottman curl predicador con mancuerna",
  "2294": "Zottman curl predicador con mancuerna",
  "2297": "Stability pelota abdominales (full range hands behind head)",
  "2298": "Inverted remo en banca",
  "2300": "Inverted remo inclinado rodillas",
  "2311": "Walking en stepmill",
  "2312": "Acostado elbow a rodilla",
  "2315": "Rotary pantorrilla con máquina",
  "2317": "Sentado inclinado brazo elevación lateral con mancuerna",
  "2318": "Press de hombros v. 3 con máquina",
  "2321": "De pie inner bíceps curl v. 2 con mancuerna",
  "2327": "Agarre invertido remo con mancuerna (mujer)",
  "2328": "Estrecho push-arriba en exercise pelota",
  "2329": "Columna twist",
  "2330": "Lat jalón full range of motion con polea",
  "2331": "Cycle cross trainer",
  "2333": "Colgador de brazos colgando recto piernas",
  "2334": "Trineo acostado pantorrilla press",
  "2335": "Sentado pantorrilla press con máquina",
  "2355": "Colgador de brazos colgando inclinado rodilla piernas",
  "2363": "Agarre ancho pecho fondo en alto paralelas barras",
  "2364": "Agarre ancho pecho fondo con asistido (de rodillas)",
  "2368": "Split squats",
  "2371": "Giro ruso v. 2 con con peso",
  "2397": "Scott press con mancuerna",
  "2398": "Agarre estrecho push-arriba (en knees)",
  "2399": "Sentado twist con polea",
  "2400": "Inverse curl de piernas (en pull-up polea máquina)",
  "2401": "Bíceps curl con mancuerna (con arm blaster)",
  "2402": "Martillo curls con mancuerna (con arm blaster)",
  "2403": "Alterno bíceps curl con mancuerna (con arm blaster)",
  "2404": "Ez-barra bíceps curl (con arm blaster)",
  "2405": "Pushdown de tríceps con polea (v-barra, con arm blaster)",
  "2406": "Agarre invertido pushdown de tríceps con polea (sz-barra, con arm blaster)",
  "2407": "Bíceps curl con barra (con arm blaster)",
  "2414": "De pie curl de concentración con barra",
  "2429": "Frog abdominales",
  "2432": "Ez-barra agarre estrecho press de banca",
  "2459": "Llanta flip",
  "2462": "Pecho fondo en recto barra",
  "2464": "Thibaudeau kayak remo con polea",
  "2466": "Bridge - escalador (cross body)",
  "2470": "Acostado en suelo deltoides posterior raise con mancuerna",
  "2567": "Sentado piriformis stretch",
  "2571": "Rocking frog stretch",
  "2611": "Horizontal one prensa de piernas con máquina",
  "2612": "Jump cuerda",
  "2616": "Lateral jalón con v-barra con polea",
  "2705": "Acostado pronation en suelo con mancuerna",
  "2706": "Acostado supination en suelo con mancuerna",
  "2736": "Agarre invertido lateral jalón con máquina",
  "2741": "Ez-barra de pie agarre ancho bíceps curl",
  "2796": "Escalón-arriba zancada con mancuerna",
  "2798": "Sentadilla jump escalón posterior zancada con barra",
  "2799": "Sitted alterno elevación de piernas con barra",
  "2800": "Sitted alterno elevación de piernas con barra (mujer)",
  "2801": "Twisted elevación de piernas (mujer)",
  "2802": "Twisted elevación de piernas",
  "2803": "Supported sentadilla con mancuerna",
  "2805": "Single pierna peso muerto con stepbox support con mancuerna",
  "2808": "Sumo pull through con mancuerna",
  "2810": "Sentadilla dividida v. 2 con barra",
  "2812": "Escalón-arriba sentadilla dividida con mancuerna",
  "2963": "Captains chair recto elevación de piernas",
  "2987": "Agarre estrecho supina en fondo cage con con peso",
  "3006": "Resistance banda sentado abducción de cadera",
  "3007": "Resistance banda extensión de piernas",
  "3010": "Ez barra acostado inclinado brazos pullover",
  "3011": "Inclinado scapula flexión de brazos",
  "3012": "Scapula dips",
  "3013": "Bajo puente de glúteos en suelo",
  "3016": "Curl-arriba",
  "3017": "Pendlay remo con barra",
  "3019": "Banca pull-ups",
  "3021": "Scapula push-arriba",
  "3116": "Fixed espalda supino jalón con banda",
  "3117": "Fixed espalda agarre estrecho jalón con banda",
  "3119": "Potty sentadilla",
  "3122": "Resistance banda sentado press de hombros",
  "3123": "Resistance banda sentado bíceps curl",
  "3124": "Resistance banda sentado pecho press",
  "3132": "Potty sentadilla con support",
  "3142": "Smith sentadilla sumo",
  "3144": "Resistance banda sentado recto espalda remo",
  "3145": "Push-arriba plus",
  "3147": "Pelvic tilt",
  "3156": "Bodyweight de pie agarre estrecho one brazo remo",
  "3158": "Bodyweight de pie agarre estrecho remo",
  "3161": "Bodyweight de pie one brazo remo (con toalla)",
  "3162": "Bodyweight de pie one brazo remo",
  "3165": "Bodyweight de pie remo (con toalla)",
  "3166": "Bodyweight de pie remo",
  "3167": "Bodyweight squatting remo (con toalla)",
  "3168": "Bodyweight squatting remo",
  "3193": "Glúteo-ham raise",
  "3194": "Frankenstein sentadilla",
  "3195": "Acostado two-one curl de piernas con máquina",
  "3200": "Inclinado-over remo con v-barra con máquina",
  "3201": "Quarter abdominales",
  "3202": "Half abdominales (hombre)",
  "3203": "Prisoner half abdominales (hombre)",
  "3204": "Brazos overhead full abdominales (hombre)",
  "3211": "Kneeling push-arriba (hombre)",
  "3212": "Basic tocarse los dedos (hombre)",
  "3213": "Side-a-side tocarse los dedos (hombre)",
  "3214": "Brazos apart circular tocarse los dedos (hombre)",
  "3215": "Manos reversed clasped circular tocarse los dedos (hombre)",
  "3216": "Pecho tap push-arriba (hombre)",
  "3217": "Modified hindu push-arriba (hombre)",
  "3218": "Manos clasped circular tocarse los dedos (hombre)",
  "3219": "Scissor jumps (hombre)",
  "3220": "Astride jumps (hombre)",
  "3221": "Half rodilla bends (hombre)",
  "3222": "Semi sentadilla jump (hombre)",
  "3223": "Star jump (hombre)",
  "3224": "Jack jump (hombre)",
  "3231": "Two tocarse los dedos (hombre)",
  "3234": "Hyght mancuerna aperturas",
  "3235": "Asistido inverse curl de piernas con polea",
  "3236": "Resistance banda cadera thrusts en rodillas (mujer)",
  "3237": "Landmine elevación lateral",
  "3239": "Kneeling plancha tap hombro (hombre)",
  "3240": "Exercise pelota en el pared elevación de pantorrillas (tennis ball between knees)",
  "3241": "Exercise pelota en el pared elevación de pantorrillas (tennis ball between ankles)",
  "3281": "Smith full sentadilla",
  "3286": "Muscle arriba con con peso",
  "3287": "Elbow dips",
  "3288": "Korean dips",
  "3289": "Impossible dips",
  "3290": "One mano dominada con con peso",
  "3291": "Stalder press",
  "3292": "Elevator",
  "3293": "Archer dominada",
  "3294": "Archer flexión de brazos",
  "3295": "Frontal máquina reps",
  "3296": "Frontal máquina",
  "3297": "Espalda máquina",
  "3298": "Straddle planche",
  "3299": "Full planche",
  "3300": "Lean planche",
  "3301": "Frog planche",
  "3302": "Handstand",
  "3303": "Flag",
  "3304": "Skin el cat",
  "3305": "Thruster con barra",
  "3312": "Muscle arriba con con peso (en barra)",
  "3313": "Recto barra fondo con con peso",
  "3314": "Straddle maltese",
  "3315": "Full maltese",
  "3318": "Swing 360",
  "3327": "Full planche push-arriba",
  "3360": "Bear crawl",
  "3361": "Skater hops",
  "3418": "L-dominada",
  "3419": "L-sit en suelo",
  "3420": "V-sit en suelo",
  "3433": "Swimmer kicks v. 2 (hombre)",
  "3470": "Forward zancada (hombre)",
  "3523": "Puente de glúteos two piernas en banca (hombre)",
  "3533": "Cuádriceps",
  "3541": "Inclinado y-raise con mancuerna",
  "3542": "Inclinado t-raise con mancuerna",
  "3543": "Bodyweight drop jump sentadilla",
  "3544": "Bodyweight inclinado side plancha",
  "3545": "Inclinado alterno press con mancuerna",
  "3546": "Sentado alterno hombro con mancuerna",
  "3547": "Sentado bíceps curl a press de hombros con mancuerna",
  "3548": "Single brazo overhead carry con mancuerna",
  "3552": "Quick pies v. 2",
  "3560": "De pie alterno curl martillo y press con mancuerna",
  "3561": "Puente de glúteos march",
  "3562": "Puente de glúteos two piernas en banca con barra (hombre)",
  "3563": "One brazo jalón con polea",
  "3582": "Zancada con jump",
  "3635": "Contralateral forward zancada con mancuerna",
  "3636": "Alto rodilla against pared",
  "3637": "Carrera con rueda",
  "3638": "Push a run",
  "3639": "Inclinado rodilla acostado twist (hombre)",
  "3640": "Rodilla touch abdominales",
  "3641": "Kneeling escalón con swing con con peso",
  "3642": "Stretch zancada con con peso",
  "3643": "Cossack squats con con peso (hombre)",
  "3644": "Zancada con swing con con peso",
  "3645": "Single pierna bridge con outstretched pierna",
  "3655": "Walking rodillas altas zancada",
  "3656": "Short stride run",
  "3662": "Pike-a-cobra push-arriba",
  "3663": "Reverse plancha con pierna lift",
  "3664": "Side plancha con posterior aperturas con mancuerna",
  "3665": "Power point plancha",
  "3666": "Walking en inclinado treadmill",
  "3667": "Side acostado aducción de cadera (hombre)",
  "3669": "De pie archer",
  "3670": "Declinado abdominales con con peso",
  "3671": "Ski escalón",
  "3672": "Espalda y forth escalón",
  "3679": "Abdominales con brazos en pecho",
  "3697": "Kneeling deltoides posterior remo con polea (con cuerda) (hombre)",
  "3698": "Inchworm v. 2",
  "3699": "Hombro tap",
  "3758": "De pie pecho press con máquina",
  "3759": "Sentado buenos días con máquina",
  "3760": "Sentado abdominales v. 2 con máquina",
  "3769": "Curtsey sentadilla",
  "3785": "Inclinado push-arriba (en cajón)",
  "3888": "One brazo snatch con mancuerna",
  "5201": "Waiter bíceps curl con mancuerna",
  "0001": "3/4 abdominales",
  "0002": "45° side bend",
  "0003": "Bicicleta abdominal",
  "0006": "Toque alterno de talones",
  "0007": "Alterno lateral jalón",
  "0009": "Pecho fondo con asistido (de rodillas)",
  "0011": "Elevación de rodillas colgando con asistido",
  "0010": "Elevación de rodillas colgando con throw abajo con asistido",
  "0012": "Acostado elevación de piernas con lateral throw abajo con asistido",
  "0013": "Acostado elevación de piernas con throw abajo con asistido",
  "0014": "Motion giro ruso con asistido",
  "0015": "Paralelas agarre estrecho dominada con asistido",
  "0016": "Boca abajo isquiotibial con asistido",
  "0017": "Dominada con asistido",
  "0018": "De pie extensión de tríceps con asistido (con toalla)",
  "0019": "Tríceps fondo con asistido (de rodillas)",
  "0020": "Balance board",
  "0968": "Alterno bíceps curl con banda",
  "0969": "Alterno v-arriba con banda",
  "0970": "Asistido dominada con banda",
  "0971": "Asistido rueda abdominal con banda",
  "0980": "Inclinado-over extensión de cadera con banda",
  "0972": "Bicycle abdominales con banda",
  "0974": "Agarre estrecho jalón con banda",
  "0975": "Agarre estrecho push-arriba con banda",
  "0976": "Curl de concentración con banda",
  "0977": "Frontal elevación lateral con banda",
  "0978": "Elevación frontal con banda",
  "0979": "Horizontal pallof press con banda",
  "0981": "Jack knife abdominales con banda",
  "0983": "Kneeling one brazo jalón con banda",
  "0985": "Kneeling twisting abdominales con banda",
  "0984": "Acostado cadera internal rotation con banda",
  "0986": "One brazo overhead bíceps curl con banda",
  "0987": "One brazo single pierna sentadilla dividida con banda",
  "0988": "One brazo de pie bajo remo con banda",
  "0989": "One brazo twisting pecho press con banda",
  "0990": "One brazo twisting remo sentado con banda",
  "0991": "Pull through con banda",
  "0992": "Push abdominales con banda",
  "0993": "Reverse aperturas con banda",
  "0994": "Reverse curl de muñeca con banda",
  "0996": "Sentado cadera internal rotation con banda",
  "0997": "Press de hombros con banda",
  "0998": "Side extensión de tríceps con banda",
  "0999": "Single pierna elevación de pantorrillas con banda",
  "0023": "Alterno bíceps curl con barra",
  "0024": "Banca sentadilla frontal con barra",
  "0025": "Press de banca con barra",
  "0026": "Banca sentadilla con barra",
  "0027": "Remo inclinado con barra",
  "0028": "Clean y press con barra",
  "0029": "Clean-grip sentadilla frontal con barra",
  "0030": "Agarre estrecho press de banca con barra",
  "0031": "Curl con barra",
  "0032": "Peso muerto con barra",
  "0033": "Declinado press de banca con barra",
  "0034": "Declinado inclinado brazo pullover con barra",
  "0035": "Declinado agarre estrecho a skull press con barra",
  "0036": "Declinado agarre ancho press con barra",
  "0037": "Declinado agarre ancho pullover con barra",
  "0038": "Drag curl con barra",
  "0039": "Frontal pecho sentadilla con barra",
  "0041": "Elevación frontal con barra",
  "0040": "Elevación frontal y pullover con barra",
  "0042": "Sentadilla frontal con barra",
  "0043": "Full sentadilla con barra",
  "0044": "Buenos días con barra",
  "0045": "Guillotine press de banca con barra",
  "0046": "Sentadilla hack con barra",
  "0047": "Inclinado press de banca con barra",
  "0048": "Inclinado agarre invertido press con barra",
  "0049": "Inclinado remo con barra",
  "0050": "Inclinado hombro raise con barra",
  "0051": "Jefferson sentadilla con barra",
  "0052": "Jm press de banca con barra",
  "0053": "Jump sentadilla con barra",
  "0054": "Zancada con barra",
  "0055": "Acostado agarre estrecho press con barra",
  "0056": "Acostado agarre estrecho extensión de tríceps con barra",
  "0057": "Acostado extension con barra",
  "0058": "Acostado lifting con barra (en hip)",
  "0059": "Acostado curl predicador con barra",
  "0061": "Acostado extensión de tríceps con barra",
  "0060": "Acostado extensión de tríceps francesa con barra",
  "0063": "Estrecho stance sentadilla con barra",
  "0064": "One brazo remo inclinado con barra",
  "0065": "One brazo suelo press con barra",
  "0066": "One brazo side peso muerto con barra",
  "0067": "One brazo snatch con barra",
  "0068": "One pierna sentadilla con barra",
  "0069": "Overhead sentadilla con barra",
  "0070": "Curl predicador con barra",
  "0071": "Press abdominales con barra",
  "0072": "Boca abajo curl inclinado con barra",
  "0073": "Pullover con barra",
  "0022": "Pullover a press con barra",
  "0074": "Rack pull con barra",
  "0075": "Deltoides posterior raise con barra",
  "0076": "Deltoides posterior remo con barra",
  "0078": "Posterior zancada con barra",
  "0077": "Posterior zancada v. 2 con barra",
  "0079": "Revers curl de muñeca v. 2 con barra",
  "0080": "Curl invertido con barra",
  "0118": "Agarre invertido remo inclinado con barra",
  "0081": "Curl invertido predicador con barra",
  "0082": "Reverse curl de muñeca con barra",
  "0084": "Rollerout con barra",
  "0083": "Rollerout from banca con barra",
  "0085": "Romanian peso muerto con barra",
  "0086": "Sentado behind cabeza press militar con barra",
  "0087": "Sentado bradford rocky press con barra",
  "0088": "Sentado elevación de pantorrillas con barra",
  "0089": "Sentado agarre estrecho curl de concentración con barra",
  "0090": "Sentado buenos días con barra",
  "0091": "Sentado press overhead con barra",
  "0092": "Sentado overhead extensión de tríceps con barra",
  "0094": "Sentado twist con barra",
  "0095": "Encogimiento con barra",
  "0096": "Side inclinado v. 2 con barra",
  "0098": "Side sentadilla dividida con barra",
  "0097": "Side sentadilla dividida v. 2 con barra",
  "0099": "Single pierna sentadilla dividida con barra",
  "0100": "Skier con barra",
  "0101": "Speed sentadilla con barra",
  "0102": "Sentadilla con barra (en knees)",
  "0103": "De pie ab rollerout con barra",
  "0104": "De pie espalda curl de muñeca con barra",
  "0105": "De pie bradford press con barra",
  "0106": "De pie agarre estrecho curl con barra",
  "0107": "De pie elevación frontal over cabeza con barra",
  "0108": "De pie pierna elevación de pantorrillas con barra",
  "0109": "De pie overhead extensión de tríceps con barra",
  "0110": "De pie agarre invertido curl con barra",
  "0111": "De pie rocking pierna elevación de pantorrillas con barra",
  "0112": "De pie twist con barra",
  "0113": "De pie agarre ancho curl con barra",
  "0114": "Escalón-arriba con barra",
  "0115": "Stiff pierna buenos días con barra",
  "0116": "Recto pierna peso muerto con barra",
  "0117": "Sumo peso muerto con barra",
  "0120": "Remo vertical con barra",
  "0119": "Remo vertical v. 2 con barra",
  "0121": "Remo vertical v. 3 con barra",
  "0122": "Ancho press de banca con barra",
  "0124": "Ancho sentadilla con barra",
  "0123": "Agarre ancho remo vertical con barra",
  "0126": "Curl de muñeca con barra",
  "0125": "Curl de muñeca v. 2 con barra",
  "0127": "Zercher sentadilla con barra",
  "0128": "Battling ropes",
  "0129": "Banca fondo (knees bent)",
  "0130": "Banca extensión de cadera",
  "0139": "Bíceps estrecho pull-ups",
  "0140": "Bíceps dominada",
  "0137": "Cuerpo-arriba",
  "0138": "Bottoms-arriba",
  "0870": "Butt-ups",
  "0148": "Alterno press de hombros con polea",
  "0149": "Alterno extensión de tríceps con polea",
  "0150": "Barra lateral jalón con polea",
  "0151": "Press de banca con polea",
  "0152": "Concentration extension con polea (en knee)",
  "0153": "Cross-over lateral jalón con polea",
  "0154": "Cross-over revers aperturas con polea",
  "0155": "Cross-over variation con polea",
  "0868": "Curl con polea",
  "0157": "Peso muerto con polea",
  "0158": "Declinado aperturas con polea",
  "0159": "Declinado sentado agarre ancho remo con polea",
  "0160": "Suelo sentado agarre ancho remo con polea",
  "0161": "Forward raise con polea",
  "0162": "Elevación frontal con polea",
  "0164": "Frontal hombro raise con polea",
  "0165": "Curl martillo con polea (con cuerda)",
  "0167": "Alto remo con polea (de rodillas)",
  "0168": "Aducción de cadera con polea",
  "0169": "Inclinado press de banca con polea",
  "0171": "Inclinado aperturas con polea",
  "0170": "Inclinado aperturas con polea (en pelota de estabilidad)",
  "0172": "Inclinado pushdown con polea",
  "0173": "Inclinado extensión de tríceps con polea",
  "0174": "Judo flip con polea",
  "0860": "Kickback con polea",
  "0175": "Kneeling abdominales con polea",
  "0176": "Kneeling extensión de tríceps con polea",
  "0177": "Lateral jalón con polea (con cuerda attachment)",
  "0178": "Elevación lateral con polea",
  "0179": "Bajo aperturas con polea",
  "0180": "Bajo remo sentado con polea",
  "0182": "Acostado agarre estrecho curl con polea",
  "0184": "Acostado extension pullover con polea (con cuerda attachment)",
  "0185": "Acostado aperturas con polea",
  "0186": "Acostado extensión de tríceps v. 2 con polea",
  "0188": "Middle aperturas con polea",
  "0189": "One brazo remo inclinado con polea",
  "0190": "One brazo curl con polea",
  "0191": "One brazo lateral inclinado-over con polea",
  "0192": "One brazo elevación lateral con polea",
  "0193": "One brazo recto espalda alto remo con polea (de rodillas)",
  "0194": "Overhead extensión de tríceps con polea (cuerda attachment)",
  "0195": "Curl predicador con polea",
  "0196": "Pull through con polea (con cuerda)",
  "0198": "Jalón con polea",
  "0197": "Jalón con polea (pro lat barra)",
  "0201": "Pushdown con polea",
  "0199": "Pushdown  v. 2 con polea (straight arm)",
  "0200": "Pushdown con polea (con cuerda attachment)",
  "0202": "Deltoides posterior remo con polea (stirrups)",
  "0203": "Deltoides posterior remo con polea (con cuerda)",
  "0204": "Posterior drive con polea",
  "0205": "Posterior jalón con polea",
  "0873": "Reverse abdominales con polea",
  "0206": "Curl invertido con polea",
  "0209": "Curl invertido predicador con polea",
  "0210": "Reverse curl de muñeca con polea",
  "0207": "Agarre invertido pushdown con polea",
  "0208": "Agarre invertido recto espalda sentado alto remo con polea",
  "0211": "Russian twists con polea (en pelota de estabilidad)",
  "0212": "Sentado abdominales con polea",
  "0213": "Sentado alto remo con polea (v-barra)",
  "0214": "Sentado one brazo alterno remo con polea",
  "0215": "Sentado posterior elevación lateral con polea",
  "0861": "Remo sentado con polea",
  "0216": "Sentado hombro internal rotation con polea",
  "0218": "Sentado agarre ancho remo con polea",
  "0219": "Press de hombros con polea",
  "0220": "Encogimiento con polea",
  "0222": "Side bend con polea",
  "0221": "Side bend abdominales con polea (bosu ball)",
  "0223": "Side abdominales con polea",
  "0224": "De pie espalda curl de muñeca con polea",
  "0225": "De pie cross-over alto reverse aperturas con polea",
  "0226": "De pie abdominales con polea",
  "0874": "De pie abdominales con polea (con cuerda attachment)",
  "0227": "De pie aperturas con polea",
  "0228": "De pie extensión de cadera con polea",
  "0229": "De pie inner curl con polea",
  "0230": "De pie lift con polea",
  "0231": "De pie one brazo extensión de tríceps con polea",
  "0232": "De pie jalón con polea (con cuerda)",
  "0233": "De pie deltoides posterior remo con polea (con cuerda)",
  "0234": "De pie remo con polea (v-barra)",
  "0235": "De pie hombro external rotation con polea",
  "0236": "De pie twist remo con polea (v-barra)",
  "0238": "Recto brazo jalón con polea",
  "0237": "Recto brazo jalón con polea (con cuerda)",
  "0239": "Recto espalda remo sentado con polea",
  "0240": "Boca arriba reverse aperturas con polea",
  "0241": "Pushdown de tríceps con polea (v-barra)",
  "0242": "Tuck reverse abdominales con polea",
  "0243": "Twist con polea",
  "0862": "Twist con polea (up-down)",
  "0244": "Twisting pull con polea",
  "0245": "Supino jalón con polea",
  "0246": "Remo vertical con polea",
  "0247": "Curl de muñeca con polea",
  "0248": "Cambered barra acostado remo",
  "0251": "Pecho fondo",
  "0253": "Barbilla-ups (narrow parallel grip)",
  "0257": "Circles rodilla stretch",
  "0258": "Clock push-arriba",
  "0259": "Agarre estrecho push-arriba",
  "0260": "Cocoons",
  "0262": "Cross cuerpo abdominales",
  "0267": "Abdominales (hands overhead)",
  "0271": "Abdominales (en pelota de estabilidad)",
  "0272": "Abdominales (en pelota de estabilidad, arms straight)",
  "0274": "Abdominales suelo",
  "0276": "Dead bug",
  "0277": "Declinado abdominales",
  "0279": "Declinado push-arriba",
  "0282": "Declinado abdominales",
  "0283": "Diamond push-arriba",
  "0284": "Donkey elevación de pantorrillas",
  "0285": "Alterno bíceps curl con mancuerna",
  "0286": "Alterno side press con mancuerna",
  "0287": "Arnold press v. 2 con mancuerna",
  "0288": "Around pullover con mancuerna",
  "0289": "Press de banca con mancuerna",
  "0290": "Banca sentado press con mancuerna",
  "0291": "Banca sentadilla con mancuerna",
  "0293": "Remo inclinado con mancuerna",
  "0294": "Bíceps curl con mancuerna",
  "0295": "Clean con mancuerna",
  "0296": "Agarre estrecho press con mancuerna",
  "0297": "Curl de concentración con mancuerna",
  "0298": "Cross cuerpo curl martillo con mancuerna",
  "0299": "Cuban press con mancuerna",
  "0300": "Peso muerto con mancuerna",
  "0301": "Declinado press de banca con mancuerna",
  "0302": "Declinado aperturas con mancuerna",
  "0303": "Declinado martillo press con mancuerna",
  "0305": "Declinado encogimiento con mancuerna",
  "0304": "Declinado encogimiento v. 2 con mancuerna",
  "0306": "Declinado extensión de tríceps con mancuerna",
  "0307": "Declinado twist aperturas con mancuerna",
  "0308": "Aperturas con mancuerna",
  "0310": "Elevación frontal con mancuerna",
  "0309": "Elevación frontal v. 2 con mancuerna",
  "0311": "Full can elevación lateral con mancuerna",
  "0313": "Curl martillo con mancuerna",
  "0312": "Curl martillo v. 2 con mancuerna",
  "0314": "Inclinado press de banca con mancuerna",
  "0315": "Inclinado bíceps curl con mancuerna",
  "0316": "Inclinado breeding con mancuerna",
  "0318": "Curl inclinado con mancuerna",
  "0317": "Curl inclinado v. 2 con mancuerna",
  "0319": "Inclinado aperturas con mancuerna",
  "0320": "Curl inclinado martillo con mancuerna",
  "0321": "Inclinado martillo press con mancuerna",
  "0322": "Inclinado inner bíceps curl con mancuerna",
  "0323": "Inclinado one brazo elevación lateral con mancuerna",
  "0324": "Inclinado palm-in press con mancuerna",
  "0325": "Inclinado raise con mancuerna",
  "0326": "Inclinado posterior elevación lateral con mancuerna",
  "0327": "Inclinado remo con mancuerna",
  "0328": "Inclinado hombro raise con mancuerna",
  "0329": "Inclinado encogimiento con mancuerna",
  "0330": "Inclinado extensión de tríceps con mancuerna",
  "0331": "Inclinado twisted flyes con mancuerna",
  "0332": "Iron cross con mancuerna",
  "0333": "Kickback con mancuerna",
  "0334": "Elevación lateral con mancuerna",
  "0335": "Lateral a elevación frontal con mancuerna",
  "0336": "Zancada con mancuerna",
  "0337": "Acostado extension con mancuerna (across face)",
  "0338": "Acostado elbow press con mancuerna",
  "0863": "Acostado external hombro rotation con mancuerna",
  "0339": "Acostado femoral con mancuerna",
  "0340": "Acostado martillo press con mancuerna",
  "0341": "Acostado one brazo deltoid posterior con mancuerna",
  "0343": "Acostado one brazo press con mancuerna",
  "0342": "Acostado one brazo press v. 2 con mancuerna",
  "0344": "Acostado one brazo pronado extensión de tríceps con mancuerna",
  "0345": "Acostado one brazo posterior elevación lateral con mancuerna",
  "0346": "Acostado one brazo supino extensión de tríceps con mancuerna",
  "0347": "Acostado pronation con mancuerna",
  "0348": "Acostado posterior elevación lateral con mancuerna",
  "0349": "Acostado supination con mancuerna",
  "0350": "Acostado boca arriba curl con mancuerna",
  "0351": "Acostado extensión de tríceps con mancuerna",
  "0352": "Agarre neutro press de banca con mancuerna",
  "0292": "One brazo inclinado-over remo con mancuerna",
  "0353": "One brazo curl de concentración con mancuerna (en pelota de estabilidad)",
  "0354": "One brazo kickback con mancuerna",
  "0355": "One brazo elevación lateral con mancuerna",
  "0356": "One brazo elevación lateral con support con mancuerna",
  "0358": "One brazo reverse curl de muñeca con mancuerna",
  "0359": "One brazo reverse aperturas con mancuerna (con support)",
  "0361": "One brazo press de hombros con mancuerna",
  "0360": "One brazo press de hombros v. 2 con mancuerna",
  "0362": "One brazo extensión de tríceps con mancuerna (en banca)",
  "0363": "One brazo remo vertical con mancuerna",
  "0364": "One brazo curl de muñeca con mancuerna",
  "0365": "Over banca neutral curl de muñeca con mancuerna",
  "0366": "Over banca one brazo neutral curl de muñeca con mancuerna",
  "0367": "Over banca one brazo curl de muñeca con mancuerna",
  "0368": "Over banca revers curl de muñeca con mancuerna",
  "0369": "Over banca curl de muñeca con mancuerna",
  "0370": "Peacher curl martillo con mancuerna",
  "0371": "Plyo sentadilla con mancuerna",
  "0372": "Curl predicador con mancuerna",
  "0373": "Pronate-grip extensión de tríceps con mancuerna",
  "0374": "Boca abajo curl inclinado con mancuerna",
  "0375": "Pullover con mancuerna",
  "0376": "Raise con mancuerna",
  "0377": "Deltoides posterior row_shoulder con mancuerna",
  "0378": "Posterior aperturas con mancuerna",
  "0380": "Posterior elevación lateral con mancuerna",
  "0379": "Posterior elevación lateral con mancuerna (support head)",
  "0381": "Posterior zancada con mancuerna",
  "0382": "Revers grip bíceps curl con mancuerna",
  "0383": "Reverse aperturas con mancuerna",
  "0384": "Curl invertido predicador con mancuerna",
  "0385": "Reverse curl de muñeca con mancuerna",
  "0386": "Rotation reverse aperturas con mancuerna",
  "0387": "Sentado alterno elevación frontal con mancuerna",
  "0388": "Sentado alterno press con mancuerna",
  "0389": "Sentado banca extension con mancuerna",
  "0390": "Sentado bíceps curl con mancuerna (en pelota de estabilidad)",
  "0391": "Sentado curl con mancuerna",
  "0392": "Sentado elevación frontal con mancuerna",
  "0393": "Sentado inner bíceps curl con mancuerna",
  "0394": "Sentado kickback con mancuerna",
  "0396": "Sentado elevación lateral con mancuerna",
  "0395": "Sentado elevación lateral v. 2 con mancuerna",
  "0397": "Sentado neutral curl de muñeca con mancuerna",
  "0398": "Sentado one brazo kickback con mancuerna",
  "0399": "Sentado one brazo rotate con mancuerna",
  "0400": "Sentado one pierna elevación de pantorrillas con mancuerna",
  "0401": "Sentado palms arriba curl de muñeca con mancuerna",
  "0402": "Sentado curl predicador con mancuerna",
  "0403": "Sentado revers grip curl de concentración con mancuerna",
  "0405": "Sentado press de hombros con mancuerna",
  "0404": "Sentado press de hombros con mancuerna (parallel grip)",
  "0406": "Encogimiento con mancuerna",
  "0407": "Side bend con mancuerna",
  "0408": "Side acostado one mano raise con mancuerna",
  "0409": "Single pierna elevación de pantorrillas con mancuerna",
  "0410": "Single pierna sentadilla dividida con mancuerna",
  "0411": "Single pierna sentadilla con mancuerna",
  "0413": "Sentadilla con mancuerna",
  "0414": "De pie alterno press overhead con mancuerna",
  "0415": "De pie alterno raise con mancuerna",
  "0416": "De pie bíceps curl con mancuerna",
  "0417": "De pie elevación de pantorrillas con mancuerna",
  "0418": "De pie curl de concentración con mancuerna",
  "0419": "De pie elevación frontal above cabeza con mancuerna",
  "0420": "De pie kickback con mancuerna",
  "0421": "De pie one brazo curl de concentración con mancuerna",
  "0422": "De pie one brazo curl con mancuerna (over banca inclinada)",
  "0423": "De pie one brazo extension con mancuerna",
  "0424": "De pie one brazo palm in press con mancuerna",
  "0425": "De pie one brazo curl invertido con mancuerna",
  "0426": "De pie press overhead con mancuerna",
  "0427": "De pie palms in press con mancuerna",
  "0428": "De pie curl predicador con mancuerna",
  "0429": "De pie curl invertido con mancuerna",
  "0430": "De pie extensión de tríceps con mancuerna",
  "0431": "Escalón-arriba con mancuerna",
  "0432": "Stiff pierna peso muerto con mancuerna",
  "0433": "Recto brazo pullover con mancuerna",
  "0434": "Recto pierna peso muerto con mancuerna",
  "0436": "Press tate con mancuerna",
  "0437": "Remo vertical con mancuerna",
  "0864": "Upright hombro external rotation con mancuerna",
  "0438": "W-press con mancuerna",
  "0439": "Zottman curl con mancuerna",
  "0443": "Elbow-a-rodilla",
  "0445": "Ez barra anti gravity press",
  "0446": "Ez barra agarre estrecho curl",
  "0447": "Ez barra curl",
  "0448": "Ez barra declinado agarre estrecho face press",
  "0449": "Ez barra inclinado extensión de tríceps",
  "0450": "Ez barra jm press de banca",
  "0451": "Ez barra agarre invertido curl",
  "0452": "Ez barra agarre invertido curl predicador",
  "0453": "Ez barra sentado extensión de tríceps",
  "0454": "Ez barra spider curl",
  "0455": "Finger curls",
  "0456": "Flexion pierna abdominales (bent knee)",
  "0457": "Flexion pierna abdominales (straight arm)",
  "0458": "Suelo aperturas (con barrara)",
  "0459": "Flutter kicks",
  "0464": "Frontal plancha con twist",
  "0466": "Gironda sternum barbilla",
  "0467": "Gorilla barbilla",
  "0469": "Groin abdominales",
  "0471": "Handstand push-arriba",
  "0472": "Colgando elevación de piernas",
  "0473": "Colgando pike",
  "0474": "Colgando recto pierna cadera raise",
  "0475": "Colgando recto elevación de piernas",
  "0476": "Colgando recto twisting pierna cadera raise",
  "0484": "Cadera raise (bent knee)",
  "0489": "Hiperextensión",
  "0488": "Hiperextensión (en banca)",
  "0490": "Inclinado agarre estrecho push-arriba",
  "0491": "Inclinado pierna cadera raise (leg straight)",
  "0492": "Inclinado flexión de brazos depth jump",
  "0493": "Inclinado push-arriba",
  "0494": "Inclinado agarre invertido push-arriba",
  "0495": "Inclinado twisting abdominales",
  "0496": "Inverse curl de piernas (banca support)",
  "0499": "Inverted remo",
  "0497": "Inverted remo v. 2",
  "0498": "Inverted remo con straps",
  "0500": "Isometric wipers",
  "0501": "Jack burpee",
  "0507": "Jackknife abdominales",
  "0508": "Janda abdominales",
  "0514": "Jump sentadilla",
  "0513": "Jump sentadilla v. 2",
  "0517": "Advanced windmill con peso ruso",
  "0518": "Alterno hang clean con peso ruso",
  "0520": "Alterno press con peso ruso",
  "0519": "Alterno press en suelo con peso ruso",
  "0521": "Alterno renegade remo con peso ruso",
  "0522": "Alterno remo con peso ruso",
  "0523": "Arnold press con peso ruso",
  "0524": "Inclinado press con peso ruso",
  "0525": "Bottoms arriba clean from el hang position con peso ruso",
  "0526": "Double alterno hang clean con peso ruso",
  "0527": "Double jerk con peso ruso",
  "0528": "Double push press con peso ruso",
  "0529": "Double snatch con peso ruso",
  "0530": "Double windmill con peso ruso",
  "0531": "Extended range one brazo press en suelo con peso ruso",
  "0532": "Figure 8 con peso ruso",
  "0533": "Sentadilla frontal con peso ruso",
  "0534": "Sentadilla copa con peso ruso",
  "0535": "Hang clean con peso ruso",
  "0536": "Zancada pass through con peso ruso",
  "0537": "One brazo clean y jerk con peso ruso",
  "0538": "One brazo jerk con peso ruso",
  "0539": "One brazo press militar a el side con peso ruso",
  "0540": "One brazo push press con peso ruso",
  "0541": "One brazo remo con peso ruso",
  "0542": "One brazo snatch con peso ruso",
  "0543": "Pirate supper piernas con peso ruso",
  "0544": "Sentadilla pistol con peso ruso",
  "0545": "Plyo push-arriba con peso ruso",
  "0546": "Sentado press con peso ruso",
  "0547": "Seesaw press con peso ruso",
  "0548": "Sumo alto pull con peso ruso",
  "0549": "Swing con peso ruso",
  "0550": "Thruster con peso ruso",
  "0551": "Turkish get arriba con peso ruso (squat style)",
  "0552": "Two brazo clean con peso ruso",
  "0553": "Two brazo press militar con peso ruso",
  "0554": "Windmill con peso ruso",
  "0555": "Kick out sit",
  "0558": "Kipping muscle arriba",
  "0562": "Landmine 180",
  "0570": "Pierna pull in plano banca",
  "0571": "Alterno estrecho grip remo sentado con máquina",
  "0572": "Asistido supina con máquina",
  "0573": "Extensión de espalda con máquina",
  "0574": "Remo inclinado con máquina",
  "0575": "Bíceps curl con máquina",
  "0577": "Pecho press con máquina",
  "0576": "Pecho press con máquina",
  "0578": "Peso muerto con máquina",
  "0579": "Frontal jalón con máquina",
  "0580": "Gripless encogimiento con máquina",
  "0581": "Alto remo con máquina",
  "0582": "Kneeling curl de piernas con máquina",
  "0583": "Kneeling twist con máquina",
  "0584": "Elevación lateral con máquina",
  "0585": "Extensión de piernas con máquina",
  "0586": "Acostado curl de piernas con máquina",
  "0587": "Press militar con máquina",
  "0588": "Estrecho grip remo sentado con máquina",
  "0589": "One brazo remo inclinado con máquina",
  "0590": "One brazo press de hombros con máquina",
  "0591": "Pronado tríceps fondo con máquina",
  "0592": "Curl predicador con máquina",
  "0593": "Reverse hiperextensión con máquina",
  "0594": "Sentado elevación de pantorrillas con máquina",
  "0595": "Sentado abdominales con máquina (chest pad)",
  "0596": "Sentado aperturas con máquina",
  "0597": "Sentado abducción de cadera con máquina",
  "0598": "Sentado aducción de cadera con máquina",
  "0599": "Sentado curl de piernas con máquina",
  "0600": "Sentado elevación de piernas abdominales con máquina",
  "0602": "Sentado reverse aperturas con máquina",
  "0601": "Sentado reverse aperturas con máquina (parallel grip)",
  "0603": "Press de hombros con máquina",
  "0869": "Press de hombros v. 2 con máquina",
  "0604": "Encogimiento con máquina",
  "0605": "De pie elevación de pantorrillas con máquina",
  "0606": "T barra remo con máquina",
  "0607": "Extensión de tríceps con máquina",
  "0609": "London bridge",
  "0613": "Acostado  cuádriceps stretch (side)",
  "0620": "Acostado elevación de piernas plano banca",
  "0865": "Acostado pierna-cadera raise",
  "0624": "March sit (pared)",
  "0627": "Mixed grip supina",
  "0628": "Monster walk",
  "0630": "Escalador",
  "0631": "Muscle arriba",
  "0634": "Negative abdominales",
  "0635": "Oblique crunches suelo",
  "0636": "Olympic barra curl martillo",
  "0637": "Olympic barra extensión de tríceps",
  "0638": "One brazo supina",
  "0639": "One brazo fondo",
  "0640": "One brazo slam (con medicine ball)",
  "0641": "Otis arriba",
  "0642": "Outside pierna kick push-arriba",
  "0643": "Overhead tríceps stretch",
  "0648": "Power clean",
  "0651": "Dominada (neutral grip)",
  "0650": "Pull-in (en pelota de estabilidad)",
  "0652": "Dominada",
  "0662": "Push-arriba",
  "0653": "Push-arriba (bosu ball)",
  "0655": "Push-arriba (en pelota de estabilidad)",
  "0656": "Push-arriba (en pelota de estabilidad)",
  "0659": "Push-arriba (pared)",
  "0658": "Push-arriba  v. 2 (pared)",
  "0660": "Push-arriba agarre estrecho off mancuerna",
  "0661": "Push-arriba inside pierna kick",
  "0663": "Push-arriba medicine pelota",
  "0664": "Push-arriba a side plancha",
  "0666": "Raise single brazo push-arriba",
  "0668": "Posterior declinado bridge",
  "0669": "Posterior deltoid stretch",
  "0670": "Posterior dominada",
  "0872": "Reverse abdominales",
  "0672": "Reverse fondo",
  "0673": "Agarre invertido máquina lat jalón",
  "0674": "Agarre invertido dominada",
  "0675": "Reverse hyper extension (en pelota de estabilidad)",
  "0677": "Anilla dips",
  "0678": "Rocky dominada jalón",
  "0680": "Cuerda climb",
  "0685": "Run",
  "0684": "Run (equipment)",
  "0687": "Giro ruso",
  "0688": "Scapular dominada",
  "0689": "Sentado elevación de piernas",
  "0690": "Sentado lower espalda stretch",
  "0691": "Sentado side abdominales (pared)",
  "0697": "Self asistido inverse curl de piernas",
  "0696": "Self asistido inverse curl de piernas (en floor)",
  "0699": "Hombro tap push-arriba",
  "0705": "Side bridge v. 2",
  "0709": "Side cadera (en barraras paralelas)",
  "0710": "Side abducción de cadera",
  "0716": "Side push cuello stretch",
  "0717": "Side push-arriba",
  "0721": "Side muñeca pull stretch",
  "0720": "Side-a-side barbilla",
  "0725": "Single brazo push-arriba",
  "0727": "Single pierna elevación de pantorrillas (en a mancuerna)",
  "0730": "Single pierna platform slide",
  "0735": "Abdominales v. 2",
  "0738": "Trineo 45в° pantorrilla press",
  "0739": "Trineo 45в° prensa de piernas",
  "0740": "Trineo 45в° pierna ancho press",
  "0741": "Trineo closer sentadilla hack",
  "0742": "Trineo forward angled elevación de pantorrillas",
  "0743": "Trineo sentadilla hack",
  "0744": "Trineo acostado sentadilla",
  "0746": "Smith espalda encogimiento",
  "0747": "Smith behind cuello press",
  "0748": "Smith press de banca",
  "0749": "Smith inclinado rodilla buenos días",
  "0750": "Smith chair sentadilla",
  "0751": "Smith agarre estrecho press de banca",
  "0752": "Smith peso muerto",
  "0753": "Smith declinado press de banca",
  "0754": "Smith declinado agarre invertido press",
  "0755": "Smith sentadilla hack",
  "0756": "Smith cadera raise",
  "0757": "Smith inclinado press de banca",
  "0758": "Smith inclinado agarre invertido press",
  "0759": "Smith inclinado hombro raises",
  "0760": "Smith prensa de piernas",
  "0761": "Smith estrecho remo",
  "0762": "Smith deltoides posterior remo",
  "0763": "Smith reverse pantorrilla raises",
  "0764": "Smith agarre invertido press",
  "0765": "Smith sentado press de hombros",
  "0766": "Smith press de hombros",
  "0767": "Smith encogimiento",
  "0768": "Smith single pierna sentadilla dividida",
  "0769": "Smith sprint zancada",
  "0770": "Smith sentadilla",
  "0771": "Smith de pie espalda curl de muñeca",
  "0772": "Smith de pie behind cabeza press militar",
  "0773": "Smith de pie pierna elevación de pantorrillas",
  "0774": "Smith de pie press militar",
  "0775": "Smith remo vertical",
  "0776": "Snatch pull",
  "0777": "Spell caster",
  "0778": "Spider crawl flexión de brazos",
  "0786": "Sentadilla jerk",
  "0788": "De pie behind cuello press",
  "0794": "De pie lateral stretch",
  "0795": "De pie single curl de piernas",
  "0796": "De pie rueda abdominal",
  "0798": "Stationary bike walk",
  "0803": "Superman push-arriba",
  "0805": "Suspended abdominal fallout",
  "0806": "Suspended push-arriba",
  "0807": "Suspended reverse abdominales",
  "0808": "Suspended remo",
  "0809": "Suspended sentadilla dividida",
  "0811": "Trap barra peso muerto",
  "0814": "Tríceps fondo",
  "0812": "Tríceps fondo (banca leg)",
  "0813": "Tríceps fondo (between bancaes)",
  "0815": "Tríceps dips suelo",
  "0816": "Tríceps press",
  "0817": "Tríceps stretch",
  "0871": "Tuck abdominales",
  "0818": "Twin handle paralelas grip lat jalón",
  "0826": "Vertical elevación de piernas (en barraras paralelas)",
  "0830": "Banca fondo con con peso",
  "0832": "Abdominales con con peso",
  "0833": "Donkey elevación de pantorrillas con con peso",
  "0834": "Elevación frontal con con peso",
  "0866": "Elevación de piernas-cadera colgando con con peso",
  "0835": "Hiperextensión con con peso (en pelota de estabilidad)",
  "0840": "Overhead abdominales con con peso (en pelota de estabilidad)",
  "0841": "Dominada con con peso",
  "0844": "Round brazo con con peso",
  "0846": "Giro ruso con con peso",
  "0845": "Giro ruso con con peso (legs up)",
  "0847": "Sentado bíceps curl con con peso (en pelota de estabilidad)",
  "0849": "Sentado twist con con peso (en pelota de estabilidad)",
  "0850": "Side bend con con peso (en pelota de estabilidad)",
  "0851": "Sissy sentadilla con con peso",
  "0852": "Sentadilla con con peso",
  "0853": "De pie curl con con peso",
  "0854": "De pie mano squeeze con con peso",
  "0856": "Svend press con con peso",
  "0857": "Rueda abdominal",
  "0858": "Wind sprints",
  "0859": "Muñeca rollerer"
};
