import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Calendar, CalendarDays, CalendarRange, Target } from "lucide-react";
import { cn } from "@/lib/utils";
function ContributionRow({ icon: Icon, label, percent, contribution, color, }) {
    return (_jsxs("div", { className: "space-y-1.5", children: [_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Icon, { className: cn("h-4 w-4", color) }), _jsx("span", { className: "font-medium", children: label })] }), _jsxs("div", { className: "flex items-baseline gap-2", children: [_jsxs("span", { className: "font-bold", children: [percent, "%"] }), contribution > 0 && (_jsxs("span", { className: "text-xs text-emerald-500 font-medium", children: ["+", contribution.toFixed(1), "%"] }))] })] }), _jsx(Progress, { value: percent, className: "h-1.5" })] }));
}
export function ProgressContribution({ dailyPercent, weeklyPercent, monthlyPercent, quarterlyPercent, weeklyContribution, monthlyContribution, quarterlyContribution, }) {
    return (_jsxs(Card, { className: "p-4 md:p-5 bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Target, { className: "h-5 w-5 text-primary" }), _jsx("h3", { className: "font-bold", children: "Tu Progreso & Contribuci\u00F3n" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx(ContributionRow, { icon: Calendar, label: "Hoy", percent: dailyPercent, contribution: 0, color: "text-blue-500" }), _jsx(ContributionRow, { icon: CalendarDays, label: "Esta Semana", percent: weeklyPercent, contribution: weeklyContribution, color: "text-emerald-500" }), _jsx(ContributionRow, { icon: CalendarRange, label: "Este Mes", percent: monthlyPercent, contribution: monthlyContribution, color: "text-orange-500" }), _jsx(ContributionRow, { icon: Target, label: "Trimestre", percent: quarterlyPercent, contribution: quarterlyContribution, color: "text-purple-500" })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-4 italic", children: "\uD83D\uDCA1 Cada h\u00E1bito que completas hoy suma a tu progreso semanal, mensual y trimestral." })] }));
}
