import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Sparkles, AlertTriangle, TrendingUp, TrendingDown } from "lucide-react";
import { cn } from "@/lib/utils";
export function VisionAntiVisionPanel({ sostenPercent, mejoraPercent, focoPercent }) {
    // Visión activa = promedio de las 3 áreas
    const visionPower = Math.round((sostenPercent + mejoraPercent + focoPercent) / 3);
    const antiVisionPower = 100 - visionPower;
    const visionActive = visionPower >= 50;
    return (_jsx(Card, { className: "overflow-hidden border-2 border-primary/20", children: _jsxs("div", { className: "p-4 md:p-5 bg-gradient-to-br from-primary/5 via-background to-destructive/5", children: [_jsxs("div", { className: "text-center mb-4", children: [_jsx("h3", { className: "text-lg md:text-xl font-bold mb-1", children: "\u2696\uFE0F Balance Visi\u00F3n vs Anti-Visi\u00F3n" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Tus 3 \u00E1reas se conectan: lo que haces hoy define qui\u00E9n ser\u00E1s" })] }), _jsxs("div", { className: "grid grid-cols-3 gap-2 mb-4", children: [_jsxs("div", { className: "text-center p-2 rounded-lg bg-blue-500/10 border border-blue-500/20", children: [_jsx("div", { className: "text-xs text-muted-foreground mb-1", children: "Sost\u00E9n" }), _jsxs("div", { className: "text-lg font-bold text-blue-500", children: [sostenPercent, "%"] }), _jsx("div", { className: "text-[10px] text-muted-foreground", children: "Te mantiene" })] }), _jsxs("div", { className: "text-center p-2 rounded-lg bg-purple-500/10 border border-purple-500/20", children: [_jsx("div", { className: "text-xs text-muted-foreground mb-1", children: "Mejora" }), _jsxs("div", { className: "text-lg font-bold text-purple-500", children: [mejoraPercent, "%"] }), _jsx("div", { className: "text-[10px] text-muted-foreground", children: "Te transforma" })] }), _jsxs("div", { className: "text-center p-2 rounded-lg bg-amber-500/10 border border-amber-500/20", children: [_jsx("div", { className: "text-xs text-muted-foreground mb-1", children: "Foco" }), _jsxs("div", { className: "text-lg font-bold text-amber-500", children: [focoPercent, "%"] }), _jsx("div", { className: "text-[10px] text-muted-foreground", children: "Te avanza" })] })] }), _jsx("div", { className: "relative h-12 rounded-xl overflow-hidden border-2 border-border mb-3", children: _jsxs("div", { className: "absolute inset-0 flex", children: [_jsx("div", { className: "bg-gradient-to-r from-emerald-500 to-primary transition-all duration-700 flex items-center justify-end pr-3", style: { width: `${visionPower}%` }, children: visionPower > 15 && (_jsxs("div", { className: "flex items-center gap-1 text-xs font-bold text-white drop-shadow", children: [_jsx(Sparkles, { className: "h-3 w-3" }), visionPower, "%"] })) }), _jsx("div", { className: "bg-gradient-to-l from-destructive to-orange-500 transition-all duration-700 flex items-center pl-3", style: { width: `${antiVisionPower}%` }, children: antiVisionPower > 15 && (_jsxs("div", { className: "flex items-center gap-1 text-xs font-bold text-white drop-shadow", children: [antiVisionPower, "%", _jsx(AlertTriangle, { className: "h-3 w-3" })] })) })] }) }), _jsx("div", { className: cn("p-3 rounded-lg border-2 text-center transition-all", visionActive
                        ? "bg-emerald-500/10 border-emerald-500/30"
                        : "bg-destructive/10 border-destructive/30"), children: visionActive ? (_jsxs("div", { className: "flex items-center justify-center gap-2", children: [_jsx(TrendingUp, { className: "h-5 w-5 text-emerald-500" }), _jsx("p", { className: "text-sm font-semibold text-emerald-500", children: "\uD83C\uDF1F Tu Visi\u00F3n est\u00E1 activ\u00E1ndose. Sigue as\u00ED." })] })) : (_jsxs("div", { className: "flex items-center justify-center gap-2", children: [_jsx(TrendingDown, { className: "h-5 w-5 text-destructive" }), _jsx("p", { className: "text-sm font-semibold text-destructive", children: "\u26A0\uFE0F Tu Anti-Visi\u00F3n est\u00E1 ganando terreno. Act\u00FAa ahora." })] })) }), _jsxs("div", { className: "mt-4 grid grid-cols-3 gap-1 text-center text-[10px] text-muted-foreground", children: [_jsx("div", { children: "\uD83D\uDEE1\uFE0F Base s\u00F3lida" }), _jsx("div", { children: "\uD83D\uDE80 Crecimiento" }), _jsx("div", { children: "\uD83C\uDFAF Resultados" })] })] }) }));
}
