import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { HashRouter, Routes, Route } from "react-router-dom";
import { cn } from "@/lib/utils";
import { pullPlansIntoLocal } from "@/lib/planSync";
import { useEffect } from "react";
import { Navigation } from "./components/Navigation";
import { OfflineProvider } from "./providers/OfflineProvider";
import { useAutoTheme } from "./hooks/useAutoTheme";
import { TimeframeProvider } from "./contexts/TimeframeContext";
import { SidebarProvider, useSidebar } from "./contexts/SidebarContext";
import Index from "./pages/Index";
import Inicio2 from "./pages/Inicio2";
import NotFound from "./pages/NotFound";
import ControlRoom from "./pages/ControlRoom";
import Habits from "./pages/Habits";
import DailyRoutine from "./pages/DailyRoutine";
import ActivationRoutine from "./pages/ActivationRoutine";
import DeactivationRoutine from "./pages/DeactivationRoutine";
import Finance from "./pages/Finance";
import Projects from "./pages/Projects";
import Tasks from "./pages/Tasks";
import DailyView from "./pages/DailyView";
import WeeklyView from "./pages/WeeklyView";
import MonthlyView from "./pages/MonthlyView";
import Goals from "./pages/Goals";
import Journaling from "./pages/Journaling";
import Entrepreneurship from "./pages/Entrepreneurship";
import EntrepreneurshipDetail from "./pages/EntrepreneurshipDetail";
import University from "./pages/University";
import Tools from "./pages/Tools";
import Reminders from "./pages/Reminders";
import DayPlanner from "./pages/DayPlanner";
import Focus from "./pages/Focus";
import RoutineDay from "./pages/RoutineDay";
import PerformanceModes from "./pages/PerformanceModes";
import Systems from "./pages/Systems";
import TwelveWeekYear from "./pages/TwelveWeekYear";
import Weeks from "./pages/Weeks";
import VidaDanielEstadisticas from "./pages/VidaDanielEstadisticas";
import DailySelfReview from "./pages/DailySelfReview";
import LifeAlignment from "./pages/LifeAlignment";
import GoalAlignment from "./pages/GoalAlignment";
import ConfidenceSteps from "./pages/ConfidenceSteps";
import ReadingLibrary from "./pages/ReadingLibrary";
import MusicDashboard from "./pages/MusicDashboard";
import LanguagesDashboard from "./pages/LanguagesDashboard";
import Purpose from "./pages/Purpose";
import SettingsPage from "./pages/SettingsPage";
import PeriodicReview from "./pages/PeriodicReview";
import SprintPage from "./pages/SprintPage";
import VisionPage from "./pages/VisionPage";
import AntiVisionPage from "./pages/AntiVisionPage";
import Alimentacion from "./pages/Alimentacion";
import Gym from "./pages/Gym";
import Chess from "./pages/Chess";
import ShoppingList from "./pages/ShoppingList";
import Grocery from "./pages/Grocery";
import PlanIdentidad from "./pages/PlanIdentidad";
import MorningPrep from "./pages/MorningPrep";
import WeekendRoutine from "./pages/WeekendRoutine";
import PuntoPartida from "./pages/PuntoPartida";
import BoxeoPage from "./pages/BoxeoPage";
import VidaSocial from "./pages/VidaSocial";
import MisNecesidades from "./pages/MisNecesidades";
import Novia from "./pages/Novia";
import AreasDeVida from "./pages/AreasDeVida";
import MapaDeVidaPage from "./pages/MapaDeVida";
import Recompensas from "./pages/Recompensas";
import Paginas from "./pages/Paginas";
import Motivos from "./pages/Motivos";
import MonthlyPlanningPage from "./pages/MonthlyPlanningPage";
import TrimestralPlanningPage from "./pages/TrimestralPlanningPage";
import WeeklyPlanningPage from "./pages/WeeklyPlanningPage";
import Realidad from "./pages/Realidad";
import HabilidadesValiosas from "./pages/HabilidadesValiosas";
import ObjetivoVision1Ano from "./pages/ObjetivoVision1Ano";
import PlanManana from "./pages/PlanManana";
import EstadisticasEsfuerzo from "./pages/EstadisticasEsfuerzo";
import VisionVsRealidad from "./pages/VisionVsRealidad";
import Identidad from "./pages/Identidad";
import DestinoALlegar from "./pages/DestinoALlegar";
import AnualView from "./pages/AnualView";
const queryClient = new QueryClient();
function AppContent() {
    useAutoTheme();
    const { collapsed } = useSidebar();
    // Sincronizar planes (trimestral/mensual, overrides y progreso) desde Supabase al abrir la app
    useEffect(() => {
        pullPlansIntoLocal();
    }, []);
    return (_jsxs("div", { className: cn("pt-12 lg:pt-0 min-h-screen transition-all duration-200", collapsed ? "lg:ml-14" : "lg:ml-56"), children: [_jsx(Navigation, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Index, {}) }), _jsx(Route, { path: "/inicio-2", element: _jsx(Inicio2, {}) }), _jsx(Route, { path: "/control-room", element: _jsx(ControlRoom, {}) }), _jsx(Route, { path: "/habits", element: _jsx(Habits, {}) }), _jsx(Route, { path: "/routine", element: _jsx(DailyRoutine, {}) }), _jsx(Route, { path: "/daily-routine", element: _jsx(DailyRoutine, {}) }), _jsx(Route, { path: "/activation-routine", element: _jsx(ActivationRoutine, {}) }), _jsx(Route, { path: "/deactivation-routine", element: _jsx(DeactivationRoutine, {}) }), _jsx(Route, { path: "/weekend-routine", element: _jsx(WeekendRoutine, {}) }), _jsx(Route, { path: "/finance", element: _jsx(Finance, {}) }), _jsx(Route, { path: "/projects", element: _jsx(Projects, {}) }), _jsx(Route, { path: "/tasks", element: _jsx(Tasks, {}) }), _jsx(Route, { path: "/daily", element: _jsx(DailyView, {}) }), _jsx(Route, { path: "/weekly", element: _jsx(WeeklyView, {}) }), _jsx(Route, { path: "/monthly", element: _jsx(MonthlyView, {}) }), _jsx(Route, { path: "/monthly-planning", element: _jsx(MonthlyPlanningPage, {}) }), _jsx(Route, { path: "/trimestral-planning", element: _jsx(TrimestralPlanningPage, {}) }), _jsx(Route, { path: "/weekly-planning", element: _jsx(WeeklyPlanningPage, {}) }), _jsx(Route, { path: "/goals", element: _jsx(Goals, {}) }), _jsx(Route, { path: "/journaling", element: _jsx(Journaling, {}) }), _jsx(Route, { path: "/entrepreneurship", element: _jsx(Entrepreneurship, {}) }), _jsx(Route, { path: "/entrepreneurship/:id", element: _jsx(EntrepreneurshipDetail, {}) }), _jsx(Route, { path: "/university", element: _jsx(University, {}) }), _jsx(Route, { path: "/tools", element: _jsx(Tools, {}) }), _jsx(Route, { path: "/reminders", element: _jsx(Reminders, {}) }), _jsx(Route, { path: "/day-planner", element: _jsx(DayPlanner, {}) }), _jsx(Route, { path: "/focus", element: _jsx(Focus, {}) }), _jsx(Route, { path: "/routine-day", element: _jsx(RoutineDay, {}) }), _jsx(Route, { path: "/performance-modes", element: _jsx(PerformanceModes, {}) }), _jsx(Route, { path: "/systems", element: _jsx(Systems, {}) }), _jsx(Route, { path: "/sprint", element: _jsx(SprintPage, {}) }), _jsx(Route, { path: "/vision", element: _jsx(VisionPage, {}) }), _jsx(Route, { path: "/antivision", element: _jsx(AntiVisionPage, {}) }), _jsx(Route, { path: "/12-week-year", element: _jsx(TwelveWeekYear, {}) }), _jsx(Route, { path: "/3-meses", element: _jsx(TwelveWeekYear, {}) }), _jsx(Route, { path: "/anual", element: _jsx(AnualView, {}) }), _jsx(Route, { path: "/weeks", element: _jsx(Weeks, {}) }), _jsx(Route, { path: "/goal-alignment", element: _jsx(GoalAlignment, {}) }), _jsx(Route, { path: "/vida-daniel", element: _jsx(VidaDanielEstadisticas, {}) }), _jsx(Route, { path: "/self-review", element: _jsx(DailySelfReview, {}) }), _jsx(Route, { path: "/life-alignment", element: _jsx(LifeAlignment, {}) }), _jsx(Route, { path: "/areas-de-vida", element: _jsx(AreasDeVida, {}) }), _jsx(Route, { path: "/mapa-de-vida", element: _jsx(MapaDeVidaPage, {}) }), _jsx(Route, { path: "/recompensas", element: _jsx(Recompensas, {}) }), _jsx(Route, { path: "/confidence-steps", element: _jsx(ConfidenceSteps, {}) }), _jsx(Route, { path: "/reading-library", element: _jsx(ReadingLibrary, {}) }), _jsx(Route, { path: "/music-dashboard", element: _jsx(MusicDashboard, {}) }), _jsx(Route, { path: "/languages-dashboard", element: _jsx(LanguagesDashboard, {}) }), _jsx(Route, { path: "/proposito", element: _jsx(Purpose, {}) }), _jsx(Route, { path: "/settings", element: _jsx(SettingsPage, {}) }), _jsx(Route, { path: "/periodic-review", element: _jsx(PeriodicReview, {}) }), _jsx(Route, { path: "/alimentacion", element: _jsx(Alimentacion, {}) }), _jsx(Route, { path: "/gym", element: _jsx(Gym, {}) }), _jsx(Route, { path: "/chess", element: _jsx(Chess, {}) }), _jsx(Route, { path: "/grocery", element: _jsx(Grocery, {}) }), _jsx(Route, { path: "/shopping-list", element: _jsx(ShoppingList, {}) }), _jsx(Route, { path: "/identidad", element: _jsx(Identidad, {}) }), _jsx(Route, { path: "/plan-identidad", element: _jsx(PlanIdentidad, {}) }), _jsx(Route, { path: "/morning-prep", element: _jsx(MorningPrep, {}) }), _jsx(Route, { path: "/punto-partida", element: _jsx(PuntoPartida, {}) }), _jsx(Route, { path: "/boxeo", element: _jsx(BoxeoPage, {}) }), _jsx(Route, { path: "/vida-social", element: _jsx(VidaSocial, {}) }), _jsx(Route, { path: "/mis-necesidades", element: _jsx(MisNecesidades, {}) }), _jsx(Route, { path: "/novia", element: _jsx(Novia, {}) }), _jsx(Route, { path: "/motivos", element: _jsx(Motivos, {}) }), _jsx(Route, { path: "/motivos/realidad", element: _jsx(Realidad, {}) }), _jsx(Route, { path: "/paginas", element: _jsx(Paginas, {}) }), _jsx(Route, { path: "/paginas/:id", element: _jsx(Paginas, {}) }), _jsx(Route, { path: "/habilidades-valiosas", element: _jsx(HabilidadesValiosas, {}) }), _jsx(Route, { path: "/objetivo-vision-1-ano", element: _jsx(ObjetivoVision1Ano, {}) }), _jsx(Route, { path: "/plan-manana", element: _jsx(PlanManana, {}) }), _jsx(Route, { path: "/estadisticas-esfuerzo", element: _jsx(EstadisticasEsfuerzo, {}) }), _jsx(Route, { path: "/vision-vs-realidad", element: _jsx(VisionVsRealidad, {}) }), _jsx(Route, { path: "/destino-a-llegar", element: _jsx(DestinoALlegar, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] })] }));
}
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsx(TooltipProvider, { children: _jsxs(OfflineProvider, { children: [_jsx(Toaster, {}), _jsx(Sonner, {}), _jsx(HashRouter, { children: _jsx(TimeframeProvider, { children: _jsx(SidebarProvider, { children: _jsx(AppContent, {}) }) }) })] }) }) }));
export default App;
