// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import {
  SUPABASE_PROJECT_URL,
  SUPABASE_PUBLISHABLE_KEY,
  isSupabaseConfigured,
} from './env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const OFFLINE_ERROR = {
  message: 'Supabase no esta configurado: faltan VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY en .env',
  code: 'SUPABASE_NOT_CONFIGURED',
  details: null,
  hint: null,
};

const offlineResult = () => ({
  data: null,
  error: OFFLINE_ERROR,
  count: null,
  status: 400,
  statusText: 'Bad Request',
  ok: false,
});

function offlineChain(): any {
  const fn = function (): any {
    return offlineChain();
  };
  return new Proxy(fn, {
    get(_t, prop) {
      if (prop === 'then') {
        return (onOk?: any, onErr?: any) => Promise.resolve(offlineResult()).then(onOk, onErr);
      }
      if (prop === 'catch') {
        return (onErr?: any) => Promise.resolve(offlineResult()).catch(onErr);
      }
      if (prop === 'finally') {
        return (onFinally?: any) => Promise.resolve(offlineResult()).finally(onFinally);
      }
      return offlineChain();
    },
    apply() {
      return offlineChain();
    },
  });
}

function createOfflineClient(): SupabaseClient<Database> {
  const authState = { data: { session: null, user: null }, error: null };
  return new Proxy({} as unknown as SupabaseClient<Database>, {
    get(_t, prop) {
      if (prop === 'auth') {
        return new Proxy(
          {},
          {
            get(_a, p) {
              if (p === 'getSession' || p === 'getUser') return () => Promise.resolve(authState);
              if (p === 'getClaims') {
                return () => Promise.resolve({ data: null, error: OFFLINE_ERROR });
              }
              if (p === 'onAuthStateChange') {
                return () => ({ data: { subscription: { unsubscribe() {} } } });
              }
              return () => Promise.resolve({ data: null, error: OFFLINE_ERROR });
            },
          },
        );
      }
      if (prop === 'functions') {
        return { invoke: () => Promise.resolve({ data: null, error: OFFLINE_ERROR }) };
      }
      if (prop === 'rpc' || prop === 'from' || prop === 'schema' || prop === 'storage') {
        return offlineChain;
      }
      if (prop === 'channel') return () => offlineChain();
      return undefined;
    },
  });
}

export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createOfflineClient();
