import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { BadgeCheck, CheckCircle2, FileText, GraduationCap, Star } from 'lucide-react';
import { cn } from '@/lib/utils';
export function SubjectProgressCard({ subject, weightedAverage, onClick, isActive, onToggleActive, onToggleApproved }) {
    const totalTasks = subject.tasks.length;
    const completedTasks = subject.tasks.filter(t => t.completed).length;
    const taskProgress = totalTasks > 0 ? (completedTasks / totalTasks) * 100 : 0;
    const gradedExams = subject.partialExams.filter(p => p.grade !== null && p.grade !== undefined);
    const pendingExams = subject.partialExams.filter(p => p.status === 'pending');
    return (_jsx(Card, { className: cn("group cursor-pointer transition-all hover:shadow-md hover:border-primary/40 border-l-4", subject.approved ? "border-l-green-500 bg-green-50/50 dark:bg-green-950/20" : "border-l-primary/60", isActive && "ring-2 ring-primary border-l-primary"), onClick: onClick, children: _jsxs(CardContent, { className: "p-4 space-y-3", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "font-semibold text-sm truncate group-hover:text-primary transition-colors", children: subject.name }), _jsxs("div", { className: "flex items-center gap-1.5 mt-1 flex-wrap", children: [subject.approved ? (_jsxs(Badge, { className: "text-[10px] px-1.5 py-0 bg-green-600", children: [_jsx(BadgeCheck, { className: "h-3 w-3 mr-0.5 inline" }), "Aprobada"] })) : (_jsx("span", { className: "text-[10px] text-muted-foreground", children: "En curso" })), subject.professor && (_jsx("span", { className: "text-[10px] text-muted-foreground truncate", children: subject.professor }))] })] }), _jsxs("div", { className: "flex items-center gap-1 shrink-0", children: [onToggleApproved && (_jsx(Button, { variant: "ghost", size: "icon", className: cn("h-7 w-7", subject.approved ? "text-green-600" : "text-muted-foreground"), onClick: (e) => { e.stopPropagation(); onToggleApproved(); }, title: subject.approved ? "Quitar aprobación" : "Marcar como aprobada 🎉", children: _jsx(BadgeCheck, { className: cn("h-4 w-4", subject.approved && "fill-green-600 text-white") }) })), onToggleActive && (_jsx(Button, { variant: "ghost", size: "icon", className: "h-7 w-7", onClick: (e) => { e.stopPropagation(); onToggleActive(); }, title: isActive ? "Quitar como activa" : "Marcar como activa", children: _jsx(Star, { className: cn("h-4 w-4", isActive ? "fill-primary text-primary" : "text-muted-foreground") }) })), weightedAverage !== null && (_jsxs("div", { className: `text-right px-2 py-1 rounded-md ${weightedAverage >= 70 ? 'bg-green-500/10 text-green-600' :
                                        weightedAverage >= 50 ? 'bg-yellow-500/10 text-yellow-600' :
                                            'bg-destructive/10 text-destructive'}`, children: [_jsx("p", { className: "text-lg font-bold leading-none", children: Math.round(weightedAverage) }), _jsx("p", { className: "text-[10px]", children: "promedio" })] }))] })] }), totalTasks > 0 && (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex items-center justify-between text-[11px]", children: [_jsxs("span", { className: "text-muted-foreground flex items-center gap-1", children: [_jsx(CheckCircle2, { className: "h-3 w-3" }), "Tareas"] }), _jsxs("span", { className: "font-medium", children: [completedTasks, "/", totalTasks] })] }), _jsx(Progress, { value: taskProgress, className: "h-1.5" })] })), _jsxs("div", { className: "flex items-center gap-3 text-[11px] text-muted-foreground", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(FileText, { className: "h-3 w-3" }), subject.topics.length, " temas"] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(GraduationCap, { className: "h-3 w-3" }), gradedExams.length, "/", subject.partialExams.length, " parciales"] }), pendingExams.length > 0 && (_jsxs(Badge, { variant: "outline", className: "text-[10px] px-1 py-0 text-yellow-600 border-yellow-500/30", children: [pendingExams.length, " pendiente", pendingExams.length > 1 ? 's' : ''] }))] })] }) }));
}
